CREATE OR ALTER VIEW PWC_DMERRORSREPORTVIEW AS
SELECT 
    TMP.TABLEID, 
    C.DESCRIPTION CATEGORY, 
    TMP.ERRORDESC AS DESCRIPTION, 
    TMP.ERRORCOLUMN, 
    STRING_AGG(CAST(TMP.ERRORVALUE AS NVARCHAR(MAX)), '; ') AS ERRORVALUES,
    SUM(TMP.COUNTROW) AS COUNT, 
    CAST((SUM(TMP.COUNTROW) * 100.0) / COALESCE(TABLECOUNTS.TOTALROWCOUNT, 1) AS DECIMAL(5, 2)) AS PERCENTAGE
FROM (
    SELECT 
        TABLEID, 
        ERRORCOLUMN, 
        CATEGORY, 
        ERRORDESC, 
        COUNT(*) AS COUNTROW, 
        ERRORVALUE
    FROM PWCERRORTABLE 
    GROUP BY TABLEID, ERRORCOLUMN, CATEGORY, ERRORDESC, ERRORVALUE
) TMP
JOIN PWCCATEGORY C ON C.ID = TMP.CATEGORY
OUTER APPLY (
    SELECT 
        SUM(P.ROWS) AS TOTALROWCOUNT
    FROM SYS.TABLES T
    JOIN SYS.SCHEMAS S ON T.SCHEMA_ID = S.SCHEMA_ID
    JOIN SYS.PARTITIONS P ON T.OBJECT_ID = P.OBJECT_ID
    WHERE T.NAME = TMP.TABLEID
      AND P.INDEX_ID IN (0, 1)
) AS TABLECOUNTS
GROUP BY TMP.TABLEID, TMP.ERRORCOLUMN, C.DESCRIPTION, TMP.ERRORDESC, TABLECOUNTS.TOTALROWCOUNT;
