CREATE OR ALTER FUNCTION PWC_GET_LEWISE_ROWCOUNT (@TABLEID NVARCHAR(100), @DATAAREAID NVARCHAR(6))
RETURNS @ResultTable TABLE (TOTALROWCOUNT INT)
AS
BEGIN
	
	INSERT INTO @ResultTable
	SELECT COUNT(DISTINCT(ROWID)) FROM PWCERRORTABLE WHERE TABLEID = @TABLEID AND DATAAREAID = @DATAAREAID

	RETURN;

END;

