CREATE OR ALTER VIEW PWC_LEWISE_ERRORREPORTVIEW AS
SELECT * FROM (SELECT 
    TMP.TABLEID, 
    C.DESCRIPTION CATEGORY, 
    TMP.ERRORDESC AS DESCRIPTION, 
    TMP.ERRORCOLUMN, 
    STRING_AGG(CAST(TMP.ERRORVALUE AS NVARCHAR(MAx)), '; ') AS ERRORVALUES,
    SUM(TMP.COUNTROW) AS COUNT,
	TMP.DATAAREAID,
	--TABLECOUNTS.TOTALROWCOUNT AS TOTALLEROWCOUNT
    CAST((SUM(TMP.COUNTROW) * 100.0) / COALESCE(TABLECOUNTS.TOTALROWCOUNT, 1) AS DECIMAL(5, 2)) AS PERCENTAGE
FROM (
    SELECT 
        TABLEID, 
        ERRORCOLUMN, 
        CATEGORY, 
        ERRORDESC, 
        COUNT(*) AS COUNTROW, 
        ERRORVALUE,
		DATAAREAID
    FROM PWCERRORTABLE 
    GROUP BY TABLEID, ERRORCOLUMN, CATEGORY, ERRORDESC, ERRORVALUE, DATAAREAID
) TMP
JOIN PWCCATEGORY C ON C.ID = TMP.CATEGORY
OUTER APPLY PWC_GET_LEWISE_ROWCOUNT (TMP.TABLEID, TMP.DATAAREAID) TABLECOUNTS
GROUP BY TMP.TABLEID, TMP.ERRORCOLUMN, C.DESCRIPTION, TMP.ERRORDESC, TMP.DATAAREAID, TABLECOUNTS.TOTALROWCOUNT) TEMP
WHERE CATEGORY NOT LIKE 'None';