CREATE OR ALTER VIEW PWC_LEWise_TableSuccessPercentView AS
SELECT
	TMP1.TABLEID,
	TMP1.DATAAREAID,
	TMP2.SUCCESSFULROWS,
	TABLECOUNTS.TOTALROWCOUNT,
	CAST((TMP2.SUCCESSFULROWS * 100/TABLECOUNTS.TOTALROWCOUNT) AS DECIMAL(5,2)) AS SUCCESSPERCENT
	FROM 
	(SELECT  TABLEID, DATAAREAID
	FROM 
		PWCERRORTABLE
	GROUP BY 
		TABLEID, DATAAREAID)TMP1
		OUTER APPLY
		( SELECT COUNT(*) AS SUCCESSFULROWS FROM PWCERRORTABLE
			WHERE 
			PWCERRORTABLE.TABLEID = TMP1.TABLEID AND
			PWCERRORTABLE.DATAAREAID = TMP1.DATAAREAID AND
			PWCERRORTABLE.CATEGORY = 0
		) TMP2
		OUTER APPLY PWC_GET_LEWISE_ROWCOUNT (TMP1.TABLEID, TMP1.DATAAREAID) TABLECOUNTS
