CREATE OR ALTER PROCEDURE PWC_SP_InsertIntoDMTable
@TABLENAME nvarchar(100)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'dbo')
    BEGIN
        PRINT 'Schema "dbo" does not exist.';
        RETURN;
    END

    DECLARE @SchemaName NVARCHAR(MAX);
    DECLARE @SQL NVARCHAR(MAX);
    DECLARE @ColumnList NVARCHAR(MAX) = '';
	DECLARE @COLUMNNAME NVARCHAR(128);

	-- Check if the column cursor already exists and deallocate if necessary
    IF CURSOR_STATUS('global', 'COLUMN_CURSOR') >= -1
    BEGIN
        CLOSE COLUMN_CURSOR;
        DEALLOCATE COLUMN_CURSOR;
    END

	DECLARE COLUMN_CURSOR CURSOR FOR
    SELECT C.NAME FROM AXDB.SYS.VIEWS V 
	JOIN AXDB.SYS.COLUMNS  C
	ON C.OBJECT_ID = V.OBJECT_ID
	WHERE V.NAME = @TABLENAME AND V.SCHEMA_ID = 1
	AND C.NAME NOT LIKE 'DATAAREAID#%' AND C.NAME NOT LIKE 'PARTITION%'
	AND C.NAME NOT LIKE 'RECID%' AND C.NAME NOT LIKE 'RECVERSION%'
	AND C.NAME NOT LIKE 'MODIFIEDBY' AND C.NAME NOT LIKE 'MODIFIEDDATETIME'
	AND C.NAME NOT LIKE 'CREATEDBY' AND C.NAME NOT LIKE 'SYSROWVERSION%'

	OPEN COLUMN_CURSOR
	FETCH NEXT FROM COLUMN_CURSOR INTO @COLUMNNAME;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @ColumnList = @ColumnList + @COLUMNNAME + ',';
		FETCH NEXT FROM COLUMN_CURSOR INTO @COLUMNNAME
	END

	CLOSE COLUMN_CURSOR;
	DEALLOCATE COLUMN_CURSOR;

	--PRINT @COLUMNLIST
	
	-- Remove the trailing comma and space
	SET @COLUMNLIST = LEFT(@COLUMNLIST, LEN(@COLUMNLIST) - 1);

	SET @SQL = '
	INSERT INTO PWC_T_' + @TABLENAME + '
	(' + @ColumnList + ') 
	SELECT ' + @ColumnList + '
	FROM AXDB.[DBO].' + @TABLENAME + '
	';

	--PRINT @SQL;
	EXEC sp_executesql @SQL;

END;



