CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetPostingProfileDisposalEntity
AS
BEGIN
	--Mandatory field is blank
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'POSTINGPROFILEID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'POSTINGPROFILEID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		POSTINGPROFILEID = '' OR POSTINGPROFILEID IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'VALUEMODELID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'VALUEMODELID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		VALUEMODELID = '' OR VALUEMODELID IS NULL;

	-- Invalid data type
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'SALEORSCRAP' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'SALEORSCRAP enum has invalid enum values' ERRORDESC, 
		SALEORSCRAP ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		SALEORSCRAP IS NOT NULL 
		AND SALEORSCRAP NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'AssetSoldScrap');

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'ACCOUNTGROUPINGS' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'ACCOUNTGROUPINGS enum has invalid enum values' ERRORDESC, 
		ACCOUNTGROUPINGS ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		ACCOUNTGROUPINGS IS NOT NULL 
		AND ACCOUNTGROUPINGS NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'TableGroupAll');

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'POSTVALUE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'POSTVALUE enum has invalid enum values' ERRORDESC, 
		POSTVALUE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		POSTVALUE IS NOT NULL 
		AND POSTVALUE NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'AssetPostValue');

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'SALESVALUETYPE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'SALESVALUETYPE enum has invalid enum values' ERRORDESC, 
		SALESVALUETYPE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		SALESVALUETYPE IS NOT NULL 
		AND SALESVALUETYPE NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'AssetPostType');
	
	-- Duplicate occurance
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'POSTINGPROFILEID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(POSTINGPROFILEID) > 10 or LEN(VALUEMODELID) > 10 or LEN(ACCOUNTRELATION) > 20 THEN 
				'POSTINGPROFILEID, SALEORSCRAP, VALUEMODELID, ACCOUNTGROUPINGS, ACCOUNTRELATION, POSTVALUE, SALESVALUETYPE has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'POSTINGPROFILEID, SALEORSCRAP, VALUEMODELID, ACCOUNTGROUPINGS, ACCOUNTRELATION, POSTVALUE, SALESVALUETYPE has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		CONCAT('(', POSTINGPROFILEID, ', ', SALEORSCRAP, ', ', VALUEMODELID, ', ', ACCOUNTGROUPINGS, ', ', ACCOUNTRELATION, ', ', POSTVALUE, ', ', SALESVALUETYPE, ')') ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE CONCAT(LEFT(POSTINGPROFILEID, 10), SALEORSCRAP, LEFT(VALUEMODELID, 10), ACCOUNTGROUPINGS, LEFT(ACCOUNTRELATION, 20), POSTVALUE, SALESVALUETYPE, DATAAREAID) IN (
		SELECT CONCAT(LEFT(POSTINGPROFILEID, 10), SALEORSCRAP, LEFT(VALUEMODELID, 10), ACCOUNTGROUPINGS, LEFT(ACCOUNTRELATION, 20), POSTVALUE, SALESVALUETYPE, DATAAREAID) 
		FROM PWC_T_AssetPostingProfileDisposalEntity
		GROUP BY LEFT(POSTINGPROFILEID, 10), SALEORSCRAP, LEFT(VALUEMODELID, 10), ACCOUNTGROUPINGS, LEFT(ACCOUNTRELATION, 20), POSTVALUE, SALESVALUETYPE, DATAAREAID 
		HAVING COUNT(*) > 1
	);

	-- Invalid submaster reference
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.POSTINGPROFILEID) = 0 THEN 'POSTINGPROFILEID'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'POSTINGPROFILEID,[PWC_T_ASSETPOSTINGPROFILE]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.POSTINGPROFILEID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.POSTINGPROFILEID) = 0 THEN 'POSTINGPROFILEID is not present in POSTINGPROFILEID of PWC_T_ASSETPOSTINGPROFILE'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetPostingProfileEntity has error(s) in corresponding POSTINGPROFILEID'
		END ERRORDESC,
		A.POSTINGPROFILEID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileDisposalEntity A
	  LEFT JOIN PWC_T_AssetPostingProfileEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') 
		AND A.POSTINGPROFILEID = B.POSTINGPROFILEID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_ASSETPOSTINGPROFILE' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.POSTINGPROFILEID IS NOT NULL AND A.POSTINGPROFILEID != ''
	  GROUP BY TABLEID, A.PWCROWID, A.POSTINGPROFILEID, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.VALUEMODELID) = 0 THEN 'VALUEMODELID'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'VALUEMODELID,[PWC_T_AssetValueModelSetupEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.VALUEMODELID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.VALUEMODELID) = 0 THEN 'VALUEMODELID is not present in VALUEMODELID of PWC_T_AssetValueModelSetupEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetValueModelSetupEntity has error(s) in corresponding VALUEMODELID'
		END ERRORDESC,
		A.VALUEMODELID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileDisposalEntity A
	  LEFT JOIN PWC_T_AssetValueModelSetupEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') 
		AND A.VALUEMODELID = B.VALUEMODELID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetValueModelSetupEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.VALUEMODELID IS NOT NULL AND A.VALUEMODELID != ''
	  GROUP BY TABLEID, A.PWCROWID, A.VALUEMODELID, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'MAINACCOUNTIDDISPLAYVALUE'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'MAINACCOUNTIDDISPLAYVALUE,[PWC_T_MainAccountEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'MAINACCOUNTIDDISPLAYVALUE is not present in MAINACCOUNTID of PWC_T_MainAccountEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_MainAccountEntity has error(s) in corresponding MAINACCOUNTIDDISPLAYVALUE'
		END ERRORDESC,
		A.MAINACCOUNTIDDISPLAYVALUE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileDisposalEntity A
	  LEFT JOIN PWC_T_MainAccountEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
		AND A.MAINACCOUNTIDDISPLAYVALUE = B.MAINACCOUNTID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_MainAccountEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.MAINACCOUNTIDDISPLAYVALUE IS NOT NULL AND A.MAINACCOUNTIDDISPLAYVALUE != ''
	  GROUP BY TABLEID, A.PWCROWID, A.MAINACCOUNTIDDISPLAYVALUE, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'OFFSETMAINACCOUNTIDDISPLAYVALUE'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'OFFSETMAINACCOUNTIDDISPLAYVALUE,[PWC_T_MainAccountEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'OFFSETMAINACCOUNTIDDISPLAYVALUE is not present in MAINACCOUNTID of PWC_T_MainAccountEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_MainAccountEntity has error(s) in corresponding OFFSETMAINACCOUNTIDDISPLAYVALUE'
		END ERRORDESC,
		A.OFFSETMAINACCOUNTIDDISPLAYVALUE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileDisposalEntity A
	  LEFT JOIN PWC_T_MainAccountEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
		AND A.OFFSETMAINACCOUNTIDDISPLAYVALUE = B.MAINACCOUNTID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_MainAccountEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.OFFSETMAINACCOUNTIDDISPLAYVALUE IS NOT NULL AND A.OFFSETMAINACCOUNTIDDISPLAYVALUE != ''
	  GROUP BY TABLEID, A.PWCROWID, A.OFFSETMAINACCOUNTIDDISPLAYVALUE, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'ACCOUNTRELATION'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'ACCOUNTRELATION,[PWC_T_AssetGroupEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'ACCOUNTRELATION is not present in FIXEDASSETGROUPID of PWC_T_AssetGroupEntity since ACCOUNTGROUPINGS is GroupId'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetGroupEntity has error(s) in corresponding ACCOUNTRELATION'
		END ERRORDESC,
		A.ACCOUNTRELATION ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileDisposalEntity A
	  LEFT JOIN PWC_T_AssetGroupEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') 
		AND A.ACCOUNTRELATION = B.FIXEDASSETGROUPID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetGroupEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.ACCOUNTRELATION IS NOT NULL AND A.ACCOUNTRELATION != '' AND LOWER(A.ACCOUNTGROUPINGS) LIKE '%group%'
	  GROUP BY TABLEID, A.PWCROWID, A.ACCOUNTRELATION, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 'ACCOUNTRELATION'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'ACCOUNTRELATION,[PWC_T_AssetFixedAssetV2Entity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 'ACCOUNTRELATION is not present in FIXEDASSETNUMBER of PWC_T_AssetFixedAssetV2Entity since ACCOUNTGROUPINGS is Table'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetFixedAssetV2Entity has error(s) in corresponding ACCOUNTRELATION'
		END ERRORDESC,
		A.ACCOUNTRELATION ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileDisposalEntity A
	  LEFT JOIN PWC_T_AssetFixedAssetV2Entity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') 
		AND A.ACCOUNTRELATION = B.FIXEDASSETNUMBER
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetFixedAssetV2Entity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.ACCOUNTRELATION IS NOT NULL AND A.ACCOUNTRELATION != '' AND LOWER(A.ACCOUNTGROUPINGS) LIKE '%tab%'
	  GROUP BY TABLEID, A.PWCROWID, A.ACCOUNTRELATION, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	-- Other system check failed
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'ACCOUNTRELATION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		6 CATEGORY, 
		'ACCOUNTRELATION is blank when ACCOUNTGROUPINGS is not ALL' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		(ACCOUNTRELATION = '' OR ACCOUNTRELATION IS NULL) AND ACCOUNTGROUPINGS NOT LIKE 'ALL';
	
	-- Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'SALEORSCRAP' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'SALEORSCRAP is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		SALEORSCRAP = '' OR SALEORSCRAP IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'ACCOUNTGROUPINGS' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'ACCOUNTGROUPINGS is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		ACCOUNTGROUPINGS = '' OR ACCOUNTGROUPINGS IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'POSTVALUE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'POSTVALUE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		POSTVALUE = '' OR POSTVALUE IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'SALESVALUETYPE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'SALESVALUETYPE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		SALESVALUETYPE = '' OR SALESVALUETYPE IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileDisposalEntity' TABLEID, 
		'MAINACCOUNTIDDISPLAYVALUE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'MAINACCOUNTIDDISPLAYVALUE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileDisposalEntity A
	WHERE 
		MAINACCOUNTIDDISPLAYVALUE = '' OR MAINACCOUNTIDDISPLAYVALUE IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetPostingProfileDisposalEntity'
END