CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetLocationEntity
AS
BEGIN
	--Mandatory field missing:
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetLocationEntity' TABLEID, 
		'LOCATIONID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'LOCATIONID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetLocationEntity A
	WHERE 
		LOCATIONID = '' OR LOCATIONID IS NULL;

	-- Duplicate occurrence
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetLocationEntity' TABLEID, 
		'LOCATIONID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(LOCATIONID) > 10 THEN 
				'LOCATIONID has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'LOCATIONID has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		LOCATIONID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetLocationEntity A
	WHERE CONCAT(LEFT(LOCATIONID, 10), DATAAREAID) IN (
		SELECT CONCAT(LEFT(LOCATIONID, 10), DATAAREAID) 
		FROM PWC_T_AssetLocationEntity
		GROUP BY LEFT(LOCATIONID, 10), DATAAREAID 
		HAVING COUNT(*) > 1
	);

	-- String length mismatch
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetLocationEntity' AS TABLEID, 
		'LOCATIONID' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'LOCATIONID exceeds max length 10' AS ERRORDESC, 
		LOCATIONID AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetLocationEntity A
	WHERE 
		LEN(LOCATIONID) > 10;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetLocationEntity' AS TABLEID, 
		'NAME' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'NAME exceeds max length 30' AS ERRORDESC, 
		NAME AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetLocationEntity A
	WHERE 
		LEN(NAME) > 30;

	-- Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetLocationEntity' TABLEID, 
		'NAME' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'NAME is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetLocationEntity A
	WHERE 
		NAME = '' OR NAME IS NULL;


	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetLocationEntity'
END