CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetSortingEntity
AS
BEGIN
	--Mandatory field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetSortingEntity' TABLEID, 
		'IDENTIFICATION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'IDENTIFICATION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetSortingEntity A
	WHERE 
		IDENTIFICATION = '' OR IDENTIFICATION IS NULL;
	
	--Duplicate occurrance
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetSortingEntity' TABLEID, 
		'IDENTIFICATION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(IDENTIFICATION) > 10 THEN 
				'IDENTIFICATION has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'IDENTIFICATION has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		IDENTIFICATION ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetSortingEntity A
	WHERE CONCAT(LEFT(IDENTIFICATION, 10), DATAAREAID) IN (
		SELECT CONCAT(LEFT(IDENTIFICATION, 10), DATAAREAID) 
		FROM PWC_T_AssetSortingEntity
		GROUP BY LEFT(IDENTIFICATION, 10), DATAAREAID 
		HAVING COUNT(*) > 1
	);

	--String length mismatch
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetSortingEntity' AS TABLEID, 
		'IDENTIFICATION' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'IDENTIFICATION exceeds max length 10' AS ERRORDESC, 
		IDENTIFICATION AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetSortingEntity A
	WHERE 
		LEN(IDENTIFICATION) > 10;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetSortingEntity' AS TABLEID, 
		'DESCRIPTION' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'DESCRIPTION exceeds max length 60' AS ERRORDESC, 
		DESCRIPTION AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetSortingEntity A
	WHERE 
		LEN(DESCRIPTION) > 60;


	--Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetSortingEntity' TABLEID, 
		'DESCRIPTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DESCRIPTION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetSortingEntity A
	WHERE 
		DESCRIPTION = '' OR DESCRIPTION IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetSortingEntity' TABLEID, 
		'SORTING' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'SORTING is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetSortingEntity A
	WHERE 
		SORTING = '' OR SORTING IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetSortingEntity'
END