CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetGroupValueModelSetupEntity
AS
BEGIN
	--Mandatory field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'FIXEDASSETGROUPID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'FIXEDASSETGROUPID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		FIXEDASSETGROUPID = '' OR FIXEDASSETGROUPID IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'VALUEMODELID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'VALUEMODELID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		VALUEMODELID = '' OR VALUEMODELID IS NULL;
	
	--Invalid data type
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'DEPRECIATIONCONVENTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'DEPRECIATIONCONVENTION enum has invalid enum values' ERRORDESC, 
		DEPRECIATIONCONVENTION ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		DEPRECIATIONCONVENTION IS NOT NULL 
		AND DEPRECIATIONCONVENTION NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'AssetDepreciationConvention');

	-- Duplicate check:
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'FIXEDASSETGROUPID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(FIXEDASSETGROUPID) > 10 or LEN(VALUEMODELID) > 10 THEN 
				'FIXEDASSETGROUPID,VALUEMODELID has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'FIXEDASSETGROUPID,VALUEMODELID has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		CONCAT('(', FIXEDASSETGROUPID, ', ', VALUEMODELID, ')') ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE CONCAT(LEFT(FIXEDASSETGROUPID, 10), LEFT(VALUEMODELID, 10), DATAAREAID) IN (
		SELECT CONCAT(LEFT(FIXEDASSETGROUPID, 10), LEFT(VALUEMODELID, 10), DATAAREAID) 
		FROM PWC_T_AssetGroupValueModelSetupEntity
		GROUP BY LEFT(FIXEDASSETGROUPID, 10), LEFT(VALUEMODELID, 10), DATAAREAID 
		HAVING COUNT(*) > 1
	);

	-- Invalid submaster reference
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'FIXEDASSETGROUPID'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'FIXEDASSETGROUPID,[PWC_T_AssetGroupEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'FIXEDASSETGROUPID is not present in FIXEDASSETGROUPID of PWC_T_AssetGroupEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetGroupEntity has error(s) in corresponding FIXEDASSETGROUPID'
		END ERRORDESC,
		A.FIXEDASSETGROUPID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetGroupValueModelSetupEntity A
	  LEFT JOIN PWC_T_AssetGroupEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
		AND A.FIXEDASSETGROUPID = B.FIXEDASSETGROUPID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetGroupEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.FIXEDASSETGROUPID IS NOT NULL AND A.FIXEDASSETGROUPID != ''
	  GROUP BY TABLEID, A.PWCROWID, A.FIXEDASSETGROUPID, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.VALUEMODELID) = 0 THEN 'VALUEMODELID'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'VALUEMODELID,[PWC_T_AssetValueModelSetupEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.VALUEMODELID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.VALUEMODELID) = 0 THEN 'VALUEMODELID is not present in VALUEMODELID of PWC_T_AssetValueModelSetupEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetValueModelSetupEntity has error(s) in corresponding VALUEMODELID'
		END ERRORDESC,
		A.VALUEMODELID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetGroupValueModelSetupEntity A
	  LEFT JOIN PWC_T_AssetValueModelSetupEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
		AND A.VALUEMODELID = B.VALUEMODELID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetValueModelSetupEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.VALUEMODELID IS NOT NULL AND A.VALUEMODELID != ''
	  GROUP BY TABLEID, A.PWCROWID, A.VALUEMODELID, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.DEPRECIATIONPROFILEID) = 0 THEN 'DEPRECIATIONPROFILEID'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'DEPRECIATIONPROFILEID,[PWC_T_AssetDepreciationProfileEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.DEPRECIATIONPROFILEID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.DEPRECIATIONPROFILEID) = 0 THEN 'DEPRECIATIONPROFILEID is not present in DEPRECIATIONPROFILEID of PWC_T_AssetDepreciationProfileEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetDepreciationProfileEntity has error(s) in corresponding DEPRECIATIONPROFILEID'
		END ERRORDESC,
		A.DEPRECIATIONPROFILEID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetGroupValueModelSetupEntity A
	  LEFT JOIN PWC_T_AssetDepreciationProfileEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
		AND A.DEPRECIATIONPROFILEID = B.DEPRECIATIONPROFILEID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetDepreciationProfileEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.DEPRECIATIONPROFILEID IS NOT NULL AND A.DEPRECIATIONPROFILEID != ''
	  GROUP BY TABLEID, A.PWCROWID, A.DEPRECIATIONPROFILEID, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;


	-- Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'CALCULATEDEPRECIATION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'CALCULATEDEPRECIATION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		CALCULATEDEPRECIATION = '' OR CALCULATEDEPRECIATION IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'DEPRECIATIONCONVENTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DEPRECIATIONCONVENTION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		DEPRECIATIONCONVENTION = '' OR DEPRECIATIONCONVENTION IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'DEPRECIATIONPERIODS' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DEPRECIATIONPERIODS is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		DEPRECIATIONPERIODS = '' OR DEPRECIATIONPERIODS IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'SERVICELIFE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'SERVICELIFE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		SERVICELIFE = '' OR SERVICELIFE IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetGroupValueModelSetupEntity' TABLEID, 
		'DEPRECIATIONPROFILEID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DEPRECIATIONPROFILEID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetGroupValueModelSetupEntity A
	WHERE 
		DEPRECIATIONPROFILEID = '' OR DEPRECIATIONPROFILEID IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetGroupValueModelSetupEntity'
END