CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetPostingProfileEntity
AS
BEGIN
	--Mandatory field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'POSTINGPROFILEID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'POSTINGPROFILEID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		POSTINGPROFILEID = '' OR POSTINGPROFILEID IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'VALUEMODELID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'VALUEMODELID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		VALUEMODELID = '' OR VALUEMODELID IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'ACCOUNTGROUPINGS' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'ACCOUNTGROUPINGS is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		ACCOUNTGROUPINGS = '' OR ACCOUNTGROUPINGS IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'TRANSACTIONTYPE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'TRANSACTIONTYPE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		TRANSACTIONTYPE = '' OR TRANSACTIONTYPE IS NULL;
	
	-- Invalid data type
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'TRANSACTIONTYPE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'TRANSACTIONTYPE enum has invalid enum values' ERRORDESC, 
		TRANSACTIONTYPE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		TRANSACTIONTYPE IS NOT NULL 
		AND TRANSACTIONTYPE NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'AssetTransType');

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'ACCOUNTGROUPINGS' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'ACCOUNTGROUPINGS enum has invalid enum values' ERRORDESC, 
		ACCOUNTGROUPINGS ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		ACCOUNTGROUPINGS IS NOT NULL 
		AND ACCOUNTGROUPINGS NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'TableGroupAll');

	-- Duplicate occurance
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'POSTINGPROFILEID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(POSTINGPROFILEID) > 10 or LEN(VALUEMODELID) > 10 or LEN(ACCOUNTRELATION) > 20 THEN 
				'POSTINGPROFILEID, VALUEMODELID, ACCOUNTGROUPINGS, ACCOUNTRELATION, TRANSACTIONTYPE has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'POSTINGPROFILEID, VALUEMODELID, ACCOUNTGROUPINGS, ACCOUNTRELATION, TRANSACTIONTYPE has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		CONCAT('(', POSTINGPROFILEID, ', ', VALUEMODELID, ', ', ACCOUNTGROUPINGS, ', ', ACCOUNTRELATION, ', ', TRANSACTIONTYPE, ')') ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE CONCAT(LEFT(POSTINGPROFILEID, 10), LEFT(VALUEMODELID, 10), ACCOUNTGROUPINGS, DATAAREAID, LEFT(ACCOUNTRELATION, 20), TRANSACTIONTYPE) IN (
		SELECT CONCAT(LEFT(POSTINGPROFILEID, 10), LEFT(VALUEMODELID, 10), ACCOUNTGROUPINGS, DATAAREAID, LEFT(ACCOUNTRELATION, 20), TRANSACTIONTYPE) 
		FROM PWC_T_AssetPostingProfileEntity
		GROUP BY LEFT(POSTINGPROFILEID, 10), LEFT(VALUEMODELID, 10), ACCOUNTGROUPINGS, DATAAREAID, LEFT(ACCOUNTRELATION, 20), TRANSACTIONTYPE 
		HAVING COUNT(*) > 1
	);

	-- Submaster missing or has error
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'MAINACCOUNTIDDISPLAYVALUE'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'MAINACCOUNTIDDISPLAYVALUE,[PWC_T_MainAccountEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'MAINACCOUNTIDDISPLAYVALUE is not present in MAINACCOUNTID of PWC_T_MainAccountEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_MainAccountEntity has error(s) in corresponding MAINACCOUNTIDDISPLAYVALUE'
		END ERRORDESC,
		A.MAINACCOUNTIDDISPLAYVALUE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileEntity A
	  LEFT JOIN PWC_T_MainAccountEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
		AND A.MAINACCOUNTIDDISPLAYVALUE = B.MAINACCOUNTID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_MainAccountEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.MAINACCOUNTIDDISPLAYVALUE IS NOT NULL AND A.MAINACCOUNTIDDISPLAYVALUE != ''
	  GROUP BY TABLEID, A.PWCROWID, A.MAINACCOUNTIDDISPLAYVALUE, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'OFFSETMAINACCOUNTIDDISPLAYVALUE'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'OFFSETMAINACCOUNTIDDISPLAYVALUE,[PWC_T_MainAccountEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.MAINACCOUNTID) = 0 THEN 'OFFSETMAINACCOUNTIDDISPLAYVALUE is not present in MAINACCOUNTID of PWC_T_MainAccountEntity'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_MainAccountEntity has error(s) in corresponding OFFSETMAINACCOUNTIDDISPLAYVALUE'
		END ERRORDESC,
		A.OFFSETMAINACCOUNTIDDISPLAYVALUE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileEntity A
	  LEFT JOIN PWC_T_MainAccountEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
		AND A.OFFSETMAINACCOUNTIDDISPLAYVALUE = B.MAINACCOUNTID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_MainAccountEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.OFFSETMAINACCOUNTIDDISPLAYVALUE IS NOT NULL AND A.OFFSETMAINACCOUNTIDDISPLAYVALUE != ''
	  GROUP BY TABLEID, A.PWCROWID, A.OFFSETMAINACCOUNTIDDISPLAYVALUE, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'ACCOUNTRELATION'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'ACCOUNTRELATION,[PWC_T_AssetGroupEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'ACCOUNTRELATION is not present in FIXEDASSETGROUPID of PWC_T_AssetGroupEntity since ACCOUNTGROUPINGS is GroupId'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetGroupEntity has error(s) in corresponding ACCOUNTRELATION'
		END ERRORDESC,
		A.ACCOUNTRELATION ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileEntity A
	  LEFT JOIN PWC_T_AssetGroupEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') 
		AND A.ACCOUNTRELATION = B.FIXEDASSETGROUPID
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetGroupEntity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.ACCOUNTRELATION IS NOT NULL AND A.ACCOUNTRELATION != '' AND A.ACCOUNTGROUPINGS LIKE '%GROUP%'
	  GROUP BY TABLEID, A.PWCROWID, A.ACCOUNTRELATION, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	INSERT INTO PWCERRORTABLE
	SELECT * FROM (
	  SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 'ACCOUNTRELATION'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'ACCOUNTRELATION,[PWC_T_AssetFixedAssetV2Entity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 4
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
		  WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 'ACCOUNTRELATION is not present in FIXEDASSETNUMBER of PWC_T_AssetFixedAssetV2Entity since ACCOUNTGROUPING is Table'
		  WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetFixedAssetV2Entity has error(s) in corresponding ACCOUNTRELATION'
		END ERRORDESC,
		A.ACCOUNTRELATION ERRORVALUE,
		A.DATAAREAID DATAAREAID
	  FROM PWC_T_AssetPostingProfileEntity A
	  LEFT JOIN PWC_T_AssetFixedAssetV2Entity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') 
		AND A.ACCOUNTRELATION = B.FIXEDASSETNUMBER
	  LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_AssetFixedAssetV2Entity' 
		AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
		AND B.PWCROWID = E.ROWID
	  WHERE A.ACCOUNTRELATION IS NOT NULL AND A.ACCOUNTRELATION != '' AND A.ACCOUNTGROUPINGS LIKE '%TAB%'
	  GROUP BY TABLEID, A.PWCROWID, A.ACCOUNTRELATION, A.DATAAREAID
	) a
	WHERE CATEGORY IS NOT NULL;

	-- String length mismatch
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' AS TABLEID, 
		'POSTINGPROFILEID' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'POSTINGPROFILEID exceeds max length 10' AS ERRORDESC, 
		POSTINGPROFILEID AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		LEN(POSTINGPROFILEID) > 10;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' AS TABLEID, 
		'DESCRIPTION' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'DESCRIPTION exceeds max length 60' AS ERRORDESC, 
		DESCRIPTION AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		LEN(DESCRIPTION) > 60;

	-- Other system checks failed
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'ACCOUNTRELATION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		6 CATEGORY, 
		'ACCOUNTRELATION should not be blank when ACCOUNTGROUPINGS is Not All' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		(ACCOUNTRELATION = '' OR ACCOUNTRELATION IS NULL) AND ACCOUNTGROUPINGS NOT LIKE 'ALL';

	
	-- Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'DESCRIPTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DESCRIPTION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		DESCRIPTION = '' OR DESCRIPTION IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetPostingProfileEntity' TABLEID, 
		'MAINACCOUNTIDDISPLAYVALUE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'MAINACCOUNTIDDISPLAYVALUE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetPostingProfileEntity A
	WHERE 
		MAINACCOUNTIDDISPLAYVALUE = '' OR MAINACCOUNTIDDISPLAYVALUE IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetPostingProfileEntity'
END