CREATE OR ALTER PROCEDURE PWC_SP_Validate_AssetBookV2Entity
AS
BEGIN

-- Invalid data format
-- ACQUISITIONDATE HAS WRONG DATE FORMAT
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'ACQUISITIONDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'ACQUISITIONDATE has wrong date format' ERRORDESC, 
ACQUISITIONDATE ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
ACQUISITIONDATE IS NOT NULL AND ISDATE(ACQUISITIONDATE) = 0;

-- ACQUISITIONPRICE is not a real number
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'ACQUISITIONPRICE' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'ACQUISITIONPRICE is not a real number' ERRORDESC, 
ACQUISITIONPRICE ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
ACQUISITIONPRICE LIKE '%[^0-9.]%';

-- SERVICELIFE is not a real number
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'SERVICELIFE' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'SERVICELIFE is not a real number' ERRORDESC, 
SERVICELIFE ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
SERVICELIFE LIKE '%[^0-9.]%';

-- DEPRECIATIONPERIODSREMAINING is not a real number
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'DEPRECIATIONPERIODSREMAINING' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'DEPRECIATIONPERIODSREMAINING is not a real number' ERRORDESC, 
DEPRECIATIONPERIODSREMAINING ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
DEPRECIATIONPERIODSREMAINING LIKE '%[^0-9.]%';

-- EXPECTEDSCRAPVALUE is not a real number
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'EXPECTEDSCRAPVALUE' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'EXPECTEDSCRAPVALUE is not a real number' ERRORDESC, 
EXPECTEDSCRAPVALUE ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
EXPECTEDSCRAPVALUE LIKE '%[^0-9.]%';

-- SERVICELIFEMONTHS is not a valid integer
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'SERVICELIFEMONTHS' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'SERVICELIFEMONTHS is not a valid integer' ERRORDESC, 
SERVICELIFEMONTHS ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
SERVICELIFEMONTHS LIKE '%[^0-9]%';

-- DEPRECIATIONPERIODS is not a valid integer
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'DEPRECIATIONPERIODS' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'DEPRECIATIONPERIODS is not a valid integer' ERRORDESC, 
DEPRECIATIONPERIODS ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
DEPRECIATIONPERIODS LIKE '%[^0-9]%';




-- Mandatory field missing:
-- FIXEDASSETNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'FIXEDASSETNUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
1 CATEGORY, 
'FIXEDASSETNUMBER is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
FIXEDASSETNUMBER = '' OR FIXEDASSETNUMBER IS NULL;

-- BOOKID is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'BOOKID' ERRORCOLUMN, 
PWCROWID ROWID, 
1 CATEGORY, 
'BOOKID is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
BOOKID = '' OR BOOKID IS NULL;

-- FIXEDASSETGROUPID is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'FIXEDASSETGROUPID' ERRORCOLUMN, 
PWCROWID ROWID, 
1 CATEGORY, 
'FIXEDASSETGROUPID is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
FIXEDASSETGROUPID = '' OR FIXEDASSETGROUPID IS NULL;





-- Business required fields missing:
-- STATUS is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'STATUS' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'STATUS is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
STATUS = '' OR STATUS IS NULL;

-- POSTINGPROFILEID is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'POSTINGPROFILEID' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'POSTINGPROFILEID is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
POSTINGPROFILEID = '' OR POSTINGPROFILEID IS NULL;

-- ACQUISITIONMETHODID is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'ACQUISITIONMETHODID' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'ACQUISITIONMETHODID is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
ACQUISITIONMETHODID = '' OR ACQUISITIONMETHODID IS NULL;

-- ACQUISITIONDATE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'ACQUISITIONDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'ACQUISITIONDATE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
ACQUISITIONDATE = '' OR ACQUISITIONDATE IS NULL;

-- CALCULATEDEPRECIATION is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'CALCULATEDEPRECIATION' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'CALCULATEDEPRECIATION is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
CALCULATEDEPRECIATION = '' OR CALCULATEDEPRECIATION IS NULL;

-- DEPRECIATIONPROFILEID is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'DEPRECIATIONPROFILEID' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'DEPRECIATIONPROFILEID is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
DEPRECIATIONPROFILEID = '' OR DEPRECIATIONPROFILEID IS NULL;

-- PLACEDINSERVICE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'PLACEDINSERVICE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'PLACEDINSERVICE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
PLACEDINSERVICE = '' OR PLACEDINSERVICE IS NULL;

-- SERVICELIFE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'SERVICELIFE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'SERVICELIFE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
SERVICELIFE = '' OR SERVICELIFE IS NULL;

-- DEPRECIATIONPERIODS is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'DEPRECIATIONPERIODS' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'DEPRECIATIONPERIODS is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
DEPRECIATIONPERIODS = '' OR DEPRECIATIONPERIODS IS NULL;

-- DEPRECIATIONPERIODSREMAINING is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'DEPRECIATIONPERIODSREMAINING' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'DEPRECIATIONPERIODSREMAINING is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
DEPRECIATIONPERIODSREMAINING = '' OR DEPRECIATIONPERIODSREMAINING IS NULL;

-- EXPECTEDSCRAPVALUE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'EXPECTEDSCRAPVALUE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'EXPECTEDSCRAPVALUE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
EXPECTEDSCRAPVALUE = '' OR EXPECTEDSCRAPVALUE IS NULL;

-- SERVICELIFEMONTHS is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'SERVICELIFEMONTHS' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'SERVICELIFEMONTHS is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
SERVICELIFEMONTHS = '' OR SERVICELIFEMONTHS IS NULL;

-- ISMIGRATEDASSET is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'ISMIGRATEDASSET' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'ISMIGRATEDASSET is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
ISMIGRATEDASSET = '' OR ISMIGRATEDASSET IS NULL;




-- Invalid Enum Values
-- STATUS has invalid enum values
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'STATUS' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'STATUS has invalid enum values' ERRORDESC, 
STATUS ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
STATUS IS NOT NULL 
AND STATUS NOT IN (
SELECT MEMBERNAME 
FROM RETAILENUMVALUETABLE 
WHERE ENUMNAME LIKE 'AssetStatus'
);




-- Duplicate occurrence:
-- FIXEDASSETNUMBER, BOOKID has duplicate values
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_AssetBookV2Entity' TABLEID, 
    '(FIXEDASSETNUMBER, BOOKID)' ERRORCOLUMN, 
    PWCROWID ROWID, 
    3 CATEGORY, 
    CASE 
        WHEN LEN(FIXEDASSETNUMBER) > 20 OR LEN(BOOKID) > 10 THEN 
            'FIXEDASSETNUMBER, BOOKID has duplicate values upon truncation'
        ELSE 
            'FIXEDASSETNUMBER, BOOKID has duplicate values'
    END ERRORDESC, 
    CONCAT('(', FIXEDASSETNUMBER, ', ', BOOKID, ')') ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE 
    CONCAT(LEFT(FIXEDASSETNUMBER, 20), LEFT(BOOKID, 10), DATAAREAID) IN (
    SELECT CONCAT(LEFT(FIXEDASSETNUMBER, 20), LEFT(BOOKID, 10), DATAAREAID) 
    FROM PWC_T_AssetBookV2Entity
    GROUP BY LEFT(FIXEDASSETNUMBER, 20), LEFT(BOOKID, 10), DATAAREAID 
    HAVING COUNT(*) > 1
);




-- Invalid submaster reference
-- FIXEDASSETNUMBER validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_AssetBookV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 'FIXEDASSETNUMBER'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'FIXEDASSETNUMBER,[PWC_T_AssetFixedAssetV2Entity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.FIXEDASSETNUMBER) = 0 THEN 'FIXEDASSETNUMBER is not present in FIXEDASSETNUMBER of PWC_T_AssetFixedAssetV2Entity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetFixedAssetV2Entity has error(s) in corresponding FIXEDASSETNUMBER'
        END ERRORDESC,
        A.FIXEDASSETNUMBER ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_AssetBookV2Entity A
    LEFT JOIN PWC_T_AssetFixedAssetV2Entity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.FIXEDASSETNUMBER = B.FIXEDASSETNUMBER
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_AssetFixedAssetV2Entity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.FIXEDASSETNUMBER IS NOT NULL AND A.FIXEDASSETNUMBER != ''
    GROUP BY A.PWCROWID, A.FIXEDASSETNUMBER, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- FIXEDASSETGROUPID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_AssetBookV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'FIXEDASSETGROUPID'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'FIXEDASSETGROUPID,[PWC_T_AssetGroupEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.FIXEDASSETGROUPID) = 0 THEN 'FIXEDASSETGROUPID is not present in FIXEDASSETGROUPID of PWC_T_AssetGroupEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetGroupEntity has error(s) in corresponding FIXEDASSETGROUPID'
        END ERRORDESC,
        A.FIXEDASSETGROUPID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_AssetBookV2Entity A
    LEFT JOIN PWC_T_AssetGroupEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.FIXEDASSETGROUPID = B.FIXEDASSETGROUPID
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_AssetGroupEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.FIXEDASSETGROUPID IS NOT NULL AND A.FIXEDASSETGROUPID != ''
    GROUP BY A.PWCROWID, A.FIXEDASSETGROUPID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- ACQUISITIONMETHODID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_AssetBookV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.AcquisitionMethod) = 0 THEN 'ACQUISITIONMETHODID'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'ACQUISITIONMETHODID,[PWC_T_AssetAcquisitionMethodEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.AcquisitionMethod) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.AcquisitionMethod) = 0 THEN 'ACQUISITIONMETHODID is not present in AcquisitionMethod of PWC_T_AssetAcquisitionMethodEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetAcquisitionMethodEntity has error(s) in corresponding AcquisitionMethod'
        END ERRORDESC,
        A.ACQUISITIONMETHODID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_AssetBookV2Entity A
    LEFT JOIN PWC_T_AssetAcquisitionMethodEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.ACQUISITIONMETHODID = B.AcquisitionMethod
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_AssetAcquisitionMethodEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.ACQUISITIONMETHODID IS NOT NULL AND A.ACQUISITIONMETHODID != ''
    GROUP BY A.PWCROWID, A.ACQUISITIONMETHODID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- POSTINGPROFILEID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_AssetBookV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.POSTINGPROFILEID) = 0 THEN 'POSTINGPROFILEID'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'POSTINGPROFILEID,[PWC_T_AssetPostingProfileEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.POSTINGPROFILEID) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.POSTINGPROFILEID) = 0 THEN 'POSTINGPROFILEID is not present in POSTINGPROFILEID of PWC_T_AssetPostingProfileEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetPostingProfileEntity has error(s) in corresponding POSTINGPROFILEID'
        END ERRORDESC,
        A.POSTINGPROFILEID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_AssetBookV2Entity A
    LEFT JOIN PWC_T_AssetPostingProfileEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.POSTINGPROFILEID = B.POSTINGPROFILEID
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_AssetPostingProfileEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.POSTINGPROFILEID IS NOT NULL AND A.POSTINGPROFILEID != ''
    GROUP BY A.PWCROWID, A.POSTINGPROFILEID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- DEPRECIATIONPROFILEID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_AssetBookV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.DepreciationProfileId) = 0 THEN 'DEPRECIATIONPROFILEID'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'DEPRECIATIONPROFILEID,[PWC_T_AssetDepreciationProfileEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.DepreciationProfileId) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.DepreciationProfileId) = 0 THEN 'DEPRECIATIONPROFILEID is not present in DepreciationProfileId of PWC_T_AssetDepreciationProfileEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_AssetDepreciationProfileEntity has error(s) in corresponding DepreciationProfileId'
        END ERRORDESC,
        A.DEPRECIATIONPROFILEID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_AssetBookV2Entity A
    LEFT JOIN PWC_T_AssetDepreciationProfileEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.DEPRECIATIONPROFILEID = B.DepreciationProfileId
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_AssetDepreciationProfileEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.DEPRECIATIONPROFILEID IS NOT NULL AND A.DEPRECIATIONPROFILEID != ''
    GROUP BY A.PWCROWID, A.DEPRECIATIONPROFILEID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;







-- String length exceeded maximum
-- BOOKID exceeds max length 10
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_AssetBookV2Entity' TABLEID, 
'BOOKID' ERRORCOLUMN, 
PWCROWID ROWID, 
7 CATEGORY, 
'BOOKID exceeds max length 10' ERRORDESC, 
BOOKID ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_AssetBookV2Entity A
WHERE LEN(BOOKID) > 10;

EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetBookV2Entity'
END
