CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetConditionEntity
AS
BEGIN
	--Mandatory field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetConditionEntity' TABLEID, 
		'CONDITIONCODE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'CONDITIONCODE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetConditionEntity A
	WHERE 
		CONDITIONCODE = '' OR CONDITIONCODE IS NULL;
	
	--Duplicate occurance
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetConditionEntity' TABLEID, 
		'CONDITIONCODE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(CONDITIONCODE) > 20 THEN 
				'CONDITIONCODE has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'CONDITIONCODE has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		CONDITIONCODE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetConditionEntity A
	WHERE CONCAT(LEFT(CONDITIONCODE, 20), DATAAREAID) IN (
		SELECT CONCAT(LEFT(CONDITIONCODE, 20), DATAAREAID) 
		FROM PWC_T_AssetConditionEntity
		GROUP BY LEFT(CONDITIONCODE, 20), DATAAREAID 
		HAVING COUNT(*) > 1
	);

	--String length mismatch
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetConditionEntity' AS TABLEID, 
		'CONDITIONCODE' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'CONDITIONCODE exceeds max length 20' AS ERRORDESC, 
		CONDITIONCODE AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetConditionEntity A
	WHERE 
		LEN(CONDITIONCODE) > 20;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetConditionEntity' AS TABLEID, 
		'DESCRIPTION' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'DESCRIPTION exceeds max length 60' AS ERRORDESC, 
		DESCRIPTION AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetConditionEntity A
	WHERE 
		LEN(DESCRIPTION) > 60;

	--Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetConditionEntity' TABLEID, 
		'DESCRIPTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DESCRIPTION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetConditionEntity A
	WHERE 
		DESCRIPTION = '' OR DESCRIPTION IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetConditionEntity'
END