CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetValueModelSetupEntity
AS
BEGIN
	--Mandatory field is blank
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'VALUEMODELID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'VALUEMODELID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		VALUEMODELID = '' OR VALUEMODELID IS NULL;
	
	-- Invalid data type
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'POSTINGLAYER' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'POSTINGLAYER enum has invalid enum values' ERRORDESC, 
		POSTINGLAYER ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		POSTINGLAYER IS NOT NULL 
		AND POSTINGLAYER NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'CurrentOperationsTax');

	--Duplicate check
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'VALUEMODELID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(VALUEMODELID) > 10 THEN 
				'VALUEMODELID has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'VALUEMODELID has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		VALUEMODELID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE CONCAT(LEFT(VALUEMODELID, 10), DATAAREAID) IN (
		SELECT CONCAT(LEFT(VALUEMODELID, 10), DATAAREAID) 
		FROM PWC_T_AssetValueModelSetupEntity
		GROUP BY LEFT(VALUEMODELID, 10), DATAAREAID 
		HAVING COUNT(*) > 1
	);

	--String length mismatch:
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' AS TABLEID, 
		'VALUEMODELID' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'VALUEMODELID exceeds max length 10' AS ERRORDESC, 
		VALUEMODELID AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		LEN(VALUEMODELID) > 10;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' AS TABLEID, 
		'DESCRIPTION' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'DESCRIPTION exceeds max length 60' AS ERRORDESC, 
		DESCRIPTION AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		LEN(DESCRIPTION) > 60;

	-- Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'CALCULATEDEPRECIATION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'CALCULATEDEPRECIATION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		CALCULATEDEPRECIATION = '' OR CALCULATEDEPRECIATION IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'CALENDARID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'CALENDARID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		CALENDARID = '' OR CALENDARID IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'DESCRIPTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DESCRIPTION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		DESCRIPTION = '' OR DESCRIPTION IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'POSTINGLAYER' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'POSTINGLAYER is blank' ERRORDESC, 
		POSTINGLAYER ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		POSTINGLAYER = '' OR POSTINGLAYER IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_AssetValueModelSetupEntity' TABLEID, 
		'DEPRECIATIONPROFILEID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DEPRECIATIONPROFILEID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_AssetValueModelSetupEntity A
	WHERE 
		DEPRECIATIONPROFILEID = '' OR DEPRECIATIONPROFILEID IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetValueModelSetupEntity'
END