CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_AssetGroupEntity
AS
BEGIN
	--Mandatory field missing:
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' TABLEID, 
		'FIXEDASSETGROUPID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'FIXEDASSETGROUPID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE 
		FIXEDASSETGROUPID = '' OR FIXEDASSETGROUPID IS NULL;
	
	--Invalid data type
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' TABLEID, 
		'TYPE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		2 CATEGORY, 
		'TYPE has invalid enum values' ERRORDESC, 
		TYPE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE 
		TYPE IS NOT NULL 
		AND TYPE NOT IN 
		(SELECT MEMBERNAME FROM RETAILENUMVALUETABLE WHERE ENUMNAME LIKE 'AssetType');


	--Duplicate occurrence
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' TABLEID, 
		'FIXEDASSETGROUPID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(FIXEDASSETGROUPID) > 10 THEN 
				'FIXEDASSETGROUPID has duplicate values upon truncation in ' + DATAAREAID
			ELSE 'FIXEDASSETGROUPID has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		FIXEDASSETGROUPID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE CONCAT(LEFT(FIXEDASSETGROUPID, 10), DATAAREAID) IN (
		SELECT CONCAT(LEFT(FIXEDASSETGROUPID, 10), DATAAREAID) 
		FROM PwC_T_AssetGroupEntity
		GROUP BY LEFT(FIXEDASSETGROUPID, 10), DATAAREAID 
		HAVING COUNT(*) > 1
	);

	-- String length mismatch
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' AS TABLEID, 
		'FIXEDASSETGROUPID' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'FIXEDASSETGROUPID exceeds max length 10' AS ERRORDESC, 
		FIXEDASSETGROUPID AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE 
		LEN(FIXEDASSETGROUPID) > 10;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' AS TABLEID, 
		'NAME' AS ERRORCOLUMN, 
		PWCROWID AS ROWID, 
		7 AS CATEGORY, 
		'NAME exceeds max length 30' AS ERRORDESC, 
		NAME AS ERRORVALUE, 
		A.DATAAREAID AS DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE 
		LEN(NAME) > 30;

	--Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' TABLEID, 
		'AUTONUMBERFIXEDASSETS' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'AUTONUMBERFIXEDASSETS is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE 
		AUTONUMBERFIXEDASSETS = '' OR AUTONUMBERFIXEDASSETS IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' TABLEID, 
		'NAME' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'NAME is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE 
		NAME = '' OR NAME IS NULL;

	INSERT INTO PWCERRORTABLE
	SELECT 
		'PwC_T_AssetGroupEntity' TABLEID, 
		'TYPE' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'TYPE is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PwC_T_AssetGroupEntity A
	WHERE 
		TYPE = '' OR TYPE IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_AssetGroupEntity'
END