CREATE OR ALTER PROCEDURE PWC_SP_Validate_CustomerPostalAddressEntity
AS
BEGIN

-- Invalid data format
    -- ADDRESSLATITUDE is not a real number
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSLATITUDE' ERRORCOLUMN, 
        PWCROWID ROWID, 
        2 CATEGORY, 
        'ADDRESSLATITUDE is not a real number' ERRORDESC, 
        ADDRESSLATITUDE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSLATITUDE LIKE '%[^0-9.]%';

    -- ADDRESSLONGITUDE is not a real number
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSLONGITUDE' ERRORCOLUMN, 
        PWCROWID ROWID, 
        2 CATEGORY, 
        'ADDRESSLONGITUDE is not a real number' ERRORDESC, 
        ADDRESSLONGITUDE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSLONGITUDE LIKE '%[^0-9.]%';




-- Mandatory fields missing
    -- CUSTOMERACCOUNTNUMBER is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'CUSTOMERACCOUNTNUMBER' ERRORCOLUMN, 
        PWCROWID ROWID, 
        1 CATEGORY, 
        'CUSTOMERACCOUNTNUMBER is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE CUSTOMERACCOUNTNUMBER = '' OR CUSTOMERACCOUNTNUMBER IS NULL;



-- Business reqd fields missing
    -- ADDRESSLOCATIONROLES is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSLOCATIONROLES' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSLOCATIONROLES is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSLOCATIONROLES = '' OR ADDRESSLOCATIONROLES IS NULL;

    -- ADDRESSCITY is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSCITY' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSCITY is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSCITY = '' OR ADDRESSCITY IS NULL;

    -- ADDRESSCOUNTRYREGIONID is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSCOUNTRYREGIONID' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSCOUNTRYREGIONID is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSCOUNTRYREGIONID = '' OR ADDRESSCOUNTRYREGIONID IS NULL;

    -- ADDRESSDESCRIPTION is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSDESCRIPTION' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSDESCRIPTION is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSDESCRIPTION = '' OR ADDRESSDESCRIPTION IS NULL;

    -- ADDRESSLATITUDE is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSLATITUDE' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSLATITUDE is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSLATITUDE = '' OR ADDRESSLATITUDE IS NULL;

    -- ADDRESSLONGITUDE is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSLONGITUDE' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSLONGITUDE is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSLONGITUDE = '' OR ADDRESSLONGITUDE IS NULL;

    -- ADDRESSSTATE is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSSTATE' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSSTATE is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSSTATE = '' OR ADDRESSSTATE IS NULL;

    -- ADDRESSSTREET is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSSTREET' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ADDRESSSTREET is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ADDRESSSTREET = '' OR ADDRESSSTREET IS NULL;

    -- ISPRIMARY is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ISPRIMARY' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ISPRIMARY is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ISPRIMARY = '' OR ISPRIMARY IS NULL;

    -- ISROLEBUSINESS is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ISROLEBUSINESS' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ISROLEBUSINESS is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ISROLEBUSINESS = '' OR ISROLEBUSINESS IS NULL;

    -- ISROLEDELIVERY is blank
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ISROLEDELIVERY' ERRORCOLUMN, 
        PWCROWID ROWID, 
        8 CATEGORY, 
        'ISROLEDELIVERY is blank' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE ISROLEDELIVERY = '' OR ISROLEDELIVERY IS NULL;



-- Duplicate occurence
    -- CUSTOMERACCOUNTNUMBER, CUSTOMERLEGALENTITYID, DATAAREAID has duplicate values
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_CustomerPostalAddressEntity' TABLEID, 
		'(CUSTOMERACCOUNTNUMBER, CUSTOMERLEGALENTITYID)' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(CUSTOMERACCOUNTNUMBER) > 20 OR LEN(CUSTOMERLEGALENTITYID) > 10 THEN 
				'CUSTOMERACCOUNTNUMBER, CUSTOMERLEGALENTITYID has duplicate values upon truncation'
			ELSE 
				'CUSTOMERACCOUNTNUMBER, CUSTOMERLEGALENTITYID has duplicate values'
		END ERRORDESC, 
		CONCAT('(', CUSTOMERACCOUNTNUMBER, ', ', CUSTOMERLEGALENTITYID, ')') ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_CustomerPostalAddressEntity A
	WHERE 
		CONCAT(LEFT(CUSTOMERACCOUNTNUMBER, 20), LEFT(CUSTOMERLEGALENTITYID, 10), DATAAREAID) IN (
		SELECT CONCAT(LEFT(CUSTOMERACCOUNTNUMBER, 20), LEFT(CUSTOMERLEGALENTITYID, 10), DATAAREAID) 
		FROM PWC_T_CustomerPostalAddressEntity
		GROUP BY LEFT(CUSTOMERACCOUNTNUMBER, 20), LEFT(CUSTOMERLEGALENTITYID, 10), DATAAREAID 
		HAVING COUNT(*) > 1
	);




	-- Invalid submaster reference
	-- ADDRESSCOUNTRYREGIONID, ADDRESSCITY, ADDRESSSTATE validation
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (SELECT 
		'PWC_T_CustomerPostalAddressEntity' TABLEID, 
		CASE 
			WHEN COUNT(B.COUNTRYREGIONID) = 0 THEN '(ADDRESSCOUNTRYREGIONID,ADDRESSCITY,ADDRESSSTATE)'
			WHEN COUNT(E.CATEGORY) <> 0 THEN '(ADDRESSCOUNTRYREGIONID,ADDRESSCITY,ADDRESSSTATE),[PWC_T_LogisticsAddressCityEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
			WHEN COUNT(B.COUNTRYREGIONID) = 0 THEN 4
			WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
			WHEN COUNT(B.COUNTRYREGIONID) = 0 THEN 'ADDRESSCOUNTRYREGIONID, ADDRESSCITY, ADDRESSSTATE is not present in COUNTRYREGIONID, NAME, STATE of PWC_T_LogisticsAddressCityEntity'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_LogisticsAddressCityEntity has error(s) in corresponding COUNTRYREGIONID, NAME, STATE'
		END ERRORDESC, 
		CONCAT('(',A.ADDRESSCOUNTRYREGIONID,',',A.ADDRESSCITY,',',A.ADDRESSSTATE,')') ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_CustomerPostalAddressEntity A
	LEFT JOIN PWC_T_LogisticsAddressCityEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL') AND A.ADDRESSCOUNTRYREGIONID = B.COUNTRYREGIONID AND A.ADDRESSCITY = B.NAME AND A.ADDRESSSTATE = B.STATEID
	LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_LogisticsAddressCityEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
			AND B.PWCROWID = E.ROWID
	WHERE 
		A.ADDRESSCOUNTRYREGIONID IS NOT NULL AND A.ADDRESSCOUNTRYREGIONID != '' AND
		A.ADDRESSCITY IS NOT NULL AND A.ADDRESSCITY != '' AND
		A.ADDRESSSTATE IS NOT NULL AND A.ADDRESSSTATE != ''
	GROUP BY TABLEID, A.PWCROWID, A.ADDRESSCOUNTRYREGIONID, A.ADDRESSCITY, A.ADDRESSSTATE, A.DATAAREAID) a
	WHERE CATEGORY IS NOT NULL;

	-- CUSTOMERACCOUNTNUMBER validation
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (SELECT 
		'PWC_T_CustomerPostalAddressEntity' TABLEID, 
		CASE 
			WHEN COUNT(B.CUSTOMERACCOUNT) = 0 THEN 'CUSTOMERACCOUNTNUMBER'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'CUSTOMERACCOUNTNUMBER,[PWC_T_CustCustomerV3Entity]'
		END ERRORCOLUMN, 
		A.PWCROWID ROWID, 
		CASE 
			WHEN COUNT(B.CUSTOMERACCOUNT) = 0 THEN 4
			WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
			WHEN COUNT(B.CUSTOMERACCOUNT) = 0 THEN 'CUSTOMERACCOUNTNUMBER is not present in CUSTOMERACCOUNT of PWC_T_CustCustomerV3Entity'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_CustCustomerV3Entity has error(s) in corresponding CUSTOMERACCOUNT'
		END ERRORDESC,
		A.CUSTOMERACCOUNTNUMBER ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_CustomerPostalAddressEntity A
	LEFT JOIN PWC_T_CustCustomerV3Entity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') AND A.CUSTOMERACCOUNTNUMBER = B.CUSTOMERACCOUNT
	LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_CustCustomerV3Entity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
			AND B.PWCROWID = E.ROWID
	WHERE 
		A.CUSTOMERACCOUNTNUMBER IS NOT NULL AND A.CUSTOMERACCOUNTNUMBER != ''
	GROUP BY A.PWCROWID, A.CUSTOMERACCOUNTNUMBER, A.DATAAREAID) a
	WHERE CATEGORY IS NOT NULL;

	-- ADDRESSCITY validation
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (SELECT 
		'PWC_T_CustomerPostalAddressEntity' TABLEID, 
		CASE 
			WHEN COUNT(B.NAME) = 0 THEN 'ADDRESSCITY'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'ADDRESSCITY,[PWC_T_LogisticsAddressCityEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
			WHEN COUNT(B.NAME) = 0 THEN 4
			WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
			WHEN COUNT(B.NAME) = 0 THEN 'ADDRESSCITY is not present in NAME of PWC_T_LogisticsAddressCityEntity'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_LogisticsAddressCityEntity has error(s) in corresponding NAME'
		END ERRORDESC, 
		A.ADDRESSCITY ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_CustomerPostalAddressEntity A
	LEFT JOIN PWC_T_LogisticsAddressCityEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') AND A.ADDRESSCITY = B.NAME
	LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_LogisticsAddressCityEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
			AND B.PWCROWID = E.ROWID
	WHERE 
		A.ADDRESSCITY IS NOT NULL AND A.ADDRESSCITY != ''
	GROUP BY TABLEID, A.PWCROWID, A.ADDRESSCITY, A.DATAAREAID) a
	WHERE CATEGORY IS NOT NULL;

	-- ADDRESSCOUNTRYREGIONID validation
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (SELECT 
		'PWC_T_CustomerPostalAddressEntity' TABLEID, 
		CASE 
			WHEN COUNT(B.COUNTRYREGION) = 0 THEN 'ADDRESSCOUNTRYREGIONID'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'ADDRESSCOUNTRYREGIONID,[PWC_T_LogisticsAddressCountryRegionEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
			WHEN COUNT(B.COUNTRYREGION) = 0 THEN 4
			WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
			WHEN COUNT(B.COUNTRYREGION) = 0 THEN 'ADDRESSCOUNTRYREGIONID is not present in COUNTRYREGION of PWC_T_LogisticsAddressCountryRegionEntity'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_LogisticsAddressCountryRegionEntity has error(s) in corresponding COUNTRYREGION'
		END ERRORDESC, 
		A.ADDRESSCOUNTRYREGIONID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_CustomerPostalAddressEntity A
	LEFT JOIN PWC_T_LogisticsAddressCountryRegionEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') AND A.ADDRESSCOUNTRYREGIONID = B.COUNTRYREGION
	LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_LogisticsAddressCountryRegionEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
			AND B.PWCROWID = E.ROWID
	WHERE 
		A.ADDRESSCOUNTRYREGIONID IS NOT NULL AND A.ADDRESSCOUNTRYREGIONID != ''
	GROUP BY TABLEID, A.PWCROWID, A.ADDRESSCOUNTRYREGIONID, A.DATAAREAID) a
	WHERE CATEGORY IS NOT NULL;

	-- ADDRESSSTATE validation
	INSERT INTO PWCERRORTABLE
	SELECT * FROM (SELECT 
		'PWC_T_CustomerPostalAddressEntity' TABLEID, 
		CASE 
			WHEN COUNT(B.STATE) = 0 THEN 'ADDRESSSTATE'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'ADDRESSSTATE,[PWC_T_LogisticsAddressStateEntity]'
		END ERRORCOLUMN,
		A.PWCROWID ROWID, 
		CASE 
			WHEN COUNT(B.STATE) = 0 THEN 4
			WHEN COUNT(E.CATEGORY) <> 0 THEN 5
		END CATEGORY, 
		CASE 
			WHEN COUNT(B.STATE) = 0 THEN 'ADDRESSSTATE is not present in STATE of PWC_T_LogisticsAddressStateEntity'
			WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_LogisticsAddressStateEntity has error(s) in corresponding STATE'
		END ERRORDESC, 
		A.ADDRESSSTATE ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_CustomerPostalAddressEntity A
	LEFT JOIN PWC_T_LogisticsAddressStateEntity B
		ON (B.DATAAREAID = A.DATAAREAID OR UPPER(B.DATAAREAID) = 'GLOBAL' OR UPPER(A.DATAAREAID) = 'GLOBAL') AND A.ADDRESSSTATE = B.STATE
	LEFT JOIN PWCERRORTABLE E
		ON E.TABLEID = 'PWC_T_LogisticsAddressStateEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
			AND B.PWCROWID = E.ROWID
	WHERE 
		A.ADDRESSSTATE IS NOT NULL AND A.ADDRESSSTATE != ''
	GROUP BY TABLEID, A.PWCROWID, A.ADDRESSSTATE, A.DATAAREAID) a
	WHERE CATEGORY IS NOT NULL;



-- String length exceeded
    -- CUSTOMERACCOUNTNUMBER exceeds max length 20
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'CUSTOMERACCOUNTNUMBER' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'CUSTOMERACCOUNTNUMBER exceeds max length 20' ERRORDESC, 
        CUSTOMERACCOUNTNUMBER ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(CUSTOMERACCOUNTNUMBER) > 20;

    -- CUSTOMERLEGALENTITYID exceeds max length 4
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'CUSTOMERLEGALENTITYID' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'CUSTOMERLEGALENTITYID exceeds max length 4' ERRORDESC, 
        CUSTOMERLEGALENTITYID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(CUSTOMERLEGALENTITYID) > 4;

    -- ADDRESSLOCATIONROLES exceeds max length 1000
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSLOCATIONROLES' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSLOCATIONROLES exceeds max length 1000' ERRORDESC, 
        ADDRESSLOCATIONROLES ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSLOCATIONROLES) > 1000;

    -- ADDRESSCITY exceeds max length 60
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSCITY' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSCITY exceeds max length 60' ERRORDESC, 
        ADDRESSCITY ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSCITY) > 60;

    -- ADDRESSCOUNTRYREGIONID exceeds max length 10
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSCOUNTRYREGIONID' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSCOUNTRYREGIONID exceeds max length 10' ERRORDESC, 
        ADDRESSCOUNTRYREGIONID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSCOUNTRYREGIONID) > 10;

    -- ADDRESSDESCRIPTION exceeds max length 60
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSDESCRIPTION' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSDESCRIPTION exceeds max length 60' ERRORDESC, 
        ADDRESSDESCRIPTION ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSDESCRIPTION) > 60;

    -- ADDRESSPOSTBOX exceeds max length 20
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSPOSTBOX' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSPOSTBOX exceeds max length 20' ERRORDESC, 
        '' ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSPOSTBOX) > 20;

    -- ADDRESSSTATE exceeds max length 10
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSSTATE' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSSTATE exceeds max length 10' ERRORDESC, 
        ADDRESSSTATE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSSTATE) > 10;

    -- ADDRESSSTREET exceeds max length 250
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSSTREET' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSSTREET exceeds max length 250' ERRORDESC, 
        ADDRESSSTREET ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSSTREET) > 250;

    -- ADDRESSZIPCODE exceeds max length 10
    INSERT INTO PWCERRORTABLE
    SELECT 
        'PWC_T_CustomerPostalAddressEntity' TABLEID, 
        'ADDRESSZIPCODE' ERRORCOLUMN, 
        PWCROWID ROWID, 
        7 CATEGORY, 
        'ADDRESSZIPCODE exceeds max length 10' ERRORDESC, 
        ADDRESSZIPCODE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_CustomerPostalAddressEntity A
    WHERE LEN(ADDRESSZIPCODE) > 10;

    -- Calculate successful count
    EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_CustomerPostalAddressEntity';
END;