CREATE OR ALTER PROCEDURE PWC_SP_VALIDATE_LedgerChartOfAccountsEntity
AS
BEGIN
	--Mandatory field is blank
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_LedgerChartOfAccountsEntity' TABLEID, 
		'CHARTOFACCOUNTS' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'CHARTOFACCOUNTS is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_LedgerChartOfAccountsEntity A
	WHERE 
		CHARTOFACCOUNTS = '' OR CHARTOFACCOUNTS IS NULL;

	--Business required field missing
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_LedgerChartOfAccountsEntity' TABLEID, 
		'DESCRIPTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DESCRIPTION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_LedgerChartOfAccountsEntity A
	WHERE 
		DESCRIPTION = '' OR DESCRIPTION IS NULL;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_LedgerChartOfAccountsEntity'
END