CREATE OR ALTER PROCEDURE PWC_SP_Validate_PurchPurchaseOrderHeaderV2Entity
AS
BEGIN

-- Invalid data format
-- ACCOUNTINGDATE HAS WRONG DATE FORMAT
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'ACCOUNTINGDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'ACCOUNTINGDATE has wrong date format' ERRORDESC, 
ACCOUNTINGDATE ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
ACCOUNTINGDATE IS NOT NULL AND ISDATE(ACCOUNTINGDATE) = 0;

-- REQUESTEDDELIVERYDATE HAS WRONG DATE FORMAT
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'REQUESTEDDELIVERYDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'REQUESTEDDELIVERYDATE has wrong date format' ERRORDESC, 
REQUESTEDDELIVERYDATE ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
REQUESTEDDELIVERYDATE IS NOT NULL AND ISDATE(REQUESTEDDELIVERYDATE) = 0;

-- CONFIRMEDDELIVERYDATE HAS WRONG DATE FORMAT
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'CONFIRMEDDELIVERYDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'CONFIRMEDDELIVERYDATE has wrong date format' ERRORDESC, 
CONFIRMEDDELIVERYDATE ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
CONFIRMEDDELIVERYDATE IS NOT NULL AND ISDATE(CONFIRMEDDELIVERYDATE) = 0;




-- Mandatory field missing:
-- PURCHASEORDERNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'PURCHASEORDERNUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
1 CATEGORY, 
'PURCHASEORDERNUMBER is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
PURCHASEORDERNUMBER = '' OR PURCHASEORDERNUMBER IS NULL;

-- ORDERVENDORACCOUNTNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'ORDERVENDORACCOUNTNUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
1 CATEGORY, 
'ORDERVENDORACCOUNTNUMBER is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
ORDERVENDORACCOUNTNUMBER = '' OR ORDERVENDORACCOUNTNUMBER IS NULL;

-- Business required fields missing:
-- ACCOUNTINGDATE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'ACCOUNTINGDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'ACCOUNTINGDATE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
ACCOUNTINGDATE = '' OR ACCOUNTINGDATE IS NULL;

-- AREPRICESINCLUDINGSALESTAX is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'AREPRICESINCLUDINGSALESTAX' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'AREPRICESINCLUDINGSALESTAX is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
AREPRICESINCLUDINGSALESTAX = '' OR AREPRICESINCLUDINGSALESTAX IS NULL;

-- CURRENCYCODE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'CURRENCYCODE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'CURRENCYCODE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
CURRENCYCODE = '' OR CURRENCYCODE IS NULL;

-- INVOICEVENDORACCOUNTNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'INVOICEVENDORACCOUNTNUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'INVOICEVENDORACCOUNTNUMBER is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
INVOICEVENDORACCOUNTNUMBER = '' OR INVOICEVENDORACCOUNTNUMBER IS NULL;

-- REQUESTEDDELIVERYDATE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'REQUESTEDDELIVERYDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'REQUESTEDDELIVERYDATE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
REQUESTEDDELIVERYDATE = '' OR REQUESTEDDELIVERYDATE IS NULL;

-- PAYMENTTERMSNAME is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'PAYMENTTERMSNAME' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'PAYMENTTERMSNAME is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
PAYMENTTERMSNAME = '' OR PAYMENTTERMSNAME IS NULL;

-- PURCHASEORDERHEADERCREATIONMETHOD is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'PURCHASEORDERHEADERCREATIONMETHOD' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'PAYMENTTERMSNAME is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
PURCHASEORDERHEADERCREATIONMETHOD = '' OR PURCHASEORDERHEADERCREATIONMETHOD IS NULL;

-- DEFAULTRECEIVINGSITEID is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'DEFAULTRECEIVINGSITEID' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'DEFAULTRECEIVINGSITEID is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
DEFAULTRECEIVINGSITEID = '' OR DEFAULTRECEIVINGSITEID IS NULL;

-- DEFAULTRECEIVINGWAREHOUSEID is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'DEFAULTRECEIVINGWAREHOUSEID' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'DEFAULTRECEIVINGWAREHOUSEID is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
DEFAULTRECEIVINGWAREHOUSEID = '' OR DEFAULTRECEIVINGWAREHOUSEID IS NULL;

-- SALESTAXGROUPCODE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'SALESTAXGROUPCODE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'SALESTAXGROUPCODE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
SALESTAXGROUPCODE = '' OR SALESTAXGROUPCODE IS NULL;

-- VENDORPAYMENTMETHODNAME is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'VENDORPAYMENTMETHODNAME' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'VENDORPAYMENTMETHODNAME is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
VENDORPAYMENTMETHODNAME = '' OR VENDORPAYMENTMETHODNAME IS NULL;

-- CONFIRMEDDELIVERYDATE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'CONFIRMEDDELIVERYDATE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'CONFIRMEDDELIVERYDATE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
CONFIRMEDDELIVERYDATE = '' OR CONFIRMEDDELIVERYDATE IS NULL;



-- Duplicate occurrence:
-- PURCHASEORDERNUMBER has duplicate values
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
    'PURCHASEORDERNUMBER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    3 CATEGORY, 
    CASE 
        WHEN LEN(PURCHASEORDERNUMBER) > 20 THEN 
            'PURCHASEORDERNUMBER has duplicate values upon truncation'
        ELSE 
            'PURCHASEORDERNUMBER has duplicate values'
    END ERRORDESC, 
    PURCHASEORDERNUMBER ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE 
    CONCAT(LEFT(PURCHASEORDERNUMBER, 20), DATAAREAID) IN (
    SELECT CONCAT(LEFT(PURCHASEORDERNUMBER, 20), DATAAREAID) 
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity
    GROUP BY LEFT(PURCHASEORDERNUMBER, 20), DATAAREAID 
    HAVING COUNT(*) > 1
);




-- CURRENCYCODE validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.CURRENCYCODE, ', ') IS NULL THEN 'CURRENCYCODE'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'CURRENCYCODE,[PWC_T_CurrencyEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.CURRENCYCODE, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.CURRENCYCODE, ', ') IS NULL THEN 'CURRENCYCODE is not present in CURRENCYCODE of PWC_T_CurrencyEntity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_CurrencyEntity has error(s) in corresponding CURRENCYCODE'
        END ERRORDESC,
        A.CURRENCYCODE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_CurrencyEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.CURRENCYCODE = B.CURRENCYCODE
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_CurrencyEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.CURRENCYCODE IS NOT NULL AND A.CURRENCYCODE != ''
    GROUP BY A.PWCROWID, A.CURRENCYCODE, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- INVOICEVENDORACCOUNTNUMBER validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.VENDORACCOUNTNUMBER, ', ') IS NULL THEN 'INVOICEVENDORACCOUNTNUMBER'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'INVOICEVENDORACCOUNTNUMBER,[PWC_T_VendVendorV2Entity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.VENDORACCOUNTNUMBER, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.VENDORACCOUNTNUMBER, ', ') IS NULL THEN 'INVOICEVENDORACCOUNTNUMBER is not present in VENDORACCOUNTNUMBER of PWC_T_VendVendorV2Entity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_VendVendorV2Entity has error(s) in corresponding VENDORACCOUNTNUMBER'
        END ERRORDESC,
        A.INVOICEVENDORACCOUNTNUMBER ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_VendVendorV2Entity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.INVOICEVENDORACCOUNTNUMBER = B.VENDORACCOUNTNUMBER
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_VendVendorV2Entity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.INVOICEVENDORACCOUNTNUMBER IS NOT NULL AND A.INVOICEVENDORACCOUNTNUMBER != ''
    GROUP BY A.PWCROWID, A.INVOICEVENDORACCOUNTNUMBER, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- DEFAULTRECEIVINGSITEID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.SITEID, ', ') IS NULL THEN 'DEFAULTRECEIVINGSITEID'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'DEFAULTRECEIVINGSITEID,[PWC_T_InventOperationalSiteV2Entity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.SITEID, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.SITEID, ', ') IS NULL THEN 'DEFAULTRECEIVINGSITEID is not present in SITEID of PWC_T_InventOperationalSiteEntity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_InventOperationalSiteV2Entity has error(s) in corresponding SITEID'
        END ERRORDESC,
        A.DEFAULTRECEIVINGSITEID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_InventOperationalSiteV2Entity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.DEFAULTRECEIVINGSITEID = B.SITEID
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_InventOperationalSiteV2Entity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.DEFAULTRECEIVINGSITEID IS NOT NULL AND A.DEFAULTRECEIVINGSITEID != ''
    GROUP BY A.PWCROWID, A.DEFAULTRECEIVINGSITEID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- DEFAULTRECEIVINGWAREHOUSEID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.WAREHOUSEID, ', ') IS NULL THEN 'DEFAULTRECEIVINGWAREHOUSEID'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'DEFAULTRECEIVINGWAREHOUSEID,[PWC_T_InventWarehouseEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.WAREHOUSEID, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.WAREHOUSEID, ', ') IS NULL THEN 'DEFAULTRECEIVINGWAREHOUSEID is not present in WAREHOUSEID of PWC_T_InventWarehouseEntity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_InventWarehouseEntity has error(s) in corresponding WAREHOUSEID'
        END ERRORDESC,
        A.DEFAULTRECEIVINGWAREHOUSEID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_InventWarehouseEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.DEFAULTRECEIVINGWAREHOUSEID = B.WAREHOUSEID
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_InventWarehouseEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.DEFAULTRECEIVINGWAREHOUSEID IS NOT NULL AND A.DEFAULTRECEIVINGWAREHOUSEID != ''
    GROUP BY A.PWCROWID, A.DEFAULTRECEIVINGWAREHOUSEID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- ORDERVENDORACCOUNTNUMBER validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.VENDORACCOUNTNUMBER, ', ') IS NULL THEN 'ORDERVENDORACCOUNTNUMBER'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'ORDERVENDORACCOUNTNUMBER,[PWC_T_VendVendorV2Entity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.VENDORACCOUNTNUMBER, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.VENDORACCOUNTNUMBER, ', ') IS NULL THEN 'ORDERVENDORACCOUNTNUMBER is not present in VENDORACCOUNTNUMBER of PWC_T_VendVendorV2Entity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_VendVendorV2Entity has error(s) in corresponding VENDORACCOUNTNUMBER'
        END ERRORDESC,
        A.ORDERVENDORACCOUNTNUMBER ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_VendVendorV2Entity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.ORDERVENDORACCOUNTNUMBER = B.VENDORACCOUNTNUMBER
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_VendVendorV2Entity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.ORDERVENDORACCOUNTNUMBER IS NOT NULL AND A.ORDERVENDORACCOUNTNUMBER != ''
    GROUP BY A.PWCROWID, A.ORDERVENDORACCOUNTNUMBER, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- PAYMENTTERMSNAME validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.NAME, ', ') IS NULL THEN 'PAYMENTTERMSNAME'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PAYMENTTERMSNAME,[PWC_T_PaymentTermEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.NAME, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.NAME, ', ') IS NULL THEN 'PAYMENTTERMSNAME is not present in NAME of PWC_T_PaymentTermEntity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_PaymentTermEntity has error(s) in corresponding NAME'
        END ERRORDESC,
        A.PAYMENTTERMSNAME ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_PaymentTermEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.PAYMENTTERMSNAME = B.NAME
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_PaymentTermEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.PAYMENTTERMSNAME IS NOT NULL AND A.PAYMENTTERMSNAME != ''
    GROUP BY A.PWCROWID, A.PAYMENTTERMSNAME, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- SALESTAXGROUPCODE validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.TAXGROUPCODE, ', ') IS NULL THEN 'SALESTAXGROUPCODE'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'SALESTAXGROUPCODE,[PWC_T_TaxGroupEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.TAXGROUPCODE, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.TAXGROUPCODE, ', ') IS NULL THEN 'SALESTAXGROUPCODE is not present in TAXGROUPCODE of PWC_T_TaxGroupEntity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_TaxGroupEntity has error(s) in corresponding TAXGROUPCODE'
        END ERRORDESC,
        A.SALESTAXGROUPCODE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_TaxGroupEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.SALESTAXGROUPCODE = B.TAXGROUPCODE
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_TaxGroupEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.SALESTAXGROUPCODE IS NOT NULL AND A.SALESTAXGROUPCODE != ''
    GROUP BY A.PWCROWID, A.SALESTAXGROUPCODE, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- VENDORPAYMENTMETHODNAME validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.Name, ', ') IS NULL THEN 'VENDORPAYMENTMETHODNAME'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'VENDORPAYMENTMETHODNAME,[PWC_T_VendorPaymentMethodEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.Name, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.Name, ', ') IS NULL THEN 'VENDORPAYMENTMETHODNAME is not present in Name of PWC_T_VendorPaymentMethodEntity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_VendorPaymentMethodEntity has error(s) in corresponding Name'
        END ERRORDESC,
        A.VENDORPAYMENTMETHODNAME ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_VendorPaymentMethodEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.VENDORPAYMENTMETHODNAME = B.Name
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_VendorPaymentMethodEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.VENDORPAYMENTMETHODNAME IS NOT NULL AND A.VENDORPAYMENTMETHODNAME != ''
    GROUP BY A.PWCROWID, A.VENDORPAYMENTMETHODNAME, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- DEFAULTRECEIVINGWAREHOUSEID, DEFAULTRECEIVINGSITEID, DATAAREAID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
        CASE 
            WHEN STRING_AGG(B.WAREHOUSEID, ', ') IS NULL THEN '(DEFAULTRECEIVINGWAREHOUSEID,DEFAULTRECEIVINGSITEID,DATAAREAID)'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN '(DEFAULTRECEIVINGWAREHOUSEID,DEFAULTRECEIVINGSITEID,DATAAREAID),[PWC_T_InventWAREHOUSEEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN STRING_AGG(B.WAREHOUSEID, ', ') IS NULL THEN 4
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 5
        END CATEGORY, 
        CASE 
            WHEN STRING_AGG(B.WAREHOUSEID, ', ') IS NULL THEN 'DEFAULTRECEIVINGWAREHOUSEID,DEFAULTRECEIVINGSITEID,DATAAREAID is not present in WAREHOUSEID,OPERATIONALSITEID of PWC_T_InventWAREHOUSEEntity'
            WHEN STRING_AGG(E.CATEGORY, ', ') IS NOT NULL THEN 'PWC_T_InventWAREHOUSEEntity has error(s) in corresponding WAREHOUSEID, OPERATIONALSITEID'
        END ERRORDESC,
        CONCAT('(',A.DEFAULTRECEIVINGWAREHOUSEID,',',A.DEFAULTRECEIVINGSITEID,')') ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
    LEFT JOIN PWC_T_InventWAREHOUSEEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.DEFAULTRECEIVINGWAREHOUSEID = B.WAREHOUSEID 
        AND A.DEFAULTRECEIVINGSITEID = B.WAREHOUSEID 
        AND A.DATAAREAID = B.DATAAREAID
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_InventDEFAULTRECEIVINGWAREHOUSEIDEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.DEFAULTRECEIVINGWAREHOUSEID IS NOT NULL AND A.DEFAULTRECEIVINGWAREHOUSEID != ''
      AND A.DEFAULTRECEIVINGSITEID IS NOT NULL AND A.DEFAULTRECEIVINGSITEID != ''
      AND A.DATAAREAID IS NOT NULL AND A.DATAAREAID != ''
    GROUP BY A.PWCROWID, A.DEFAULTRECEIVINGWAREHOUSEID, A.DEFAULTRECEIVINGSITEID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;






-- String length exceeded maximum
-- PURCHASEORDERNUMBER exceeds max length 20
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'PURCHASEORDERNUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
7 CATEGORY, 
'PURCHASEORDERNUMBER exceeds max length 20' ERRORDESC, 
PURCHASEORDERNUMBER ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE LEN(PURCHASEORDERNUMBER) > 20;

-- DELIVERYADDRESSDESCRIPTION exceeds max length 60
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'DELIVERYADDRESSDESCRIPTION' ERRORCOLUMN, 
PWCROWID ROWID, 
7 CATEGORY, 
'DELIVERYADDRESSDESCRIPTION exceeds max length 60' ERRORDESC, 
DELIVERYADDRESSDESCRIPTION ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE LEN(DELIVERYADDRESSDESCRIPTION) > 60;

-- DELIVERYADDRESSNAME exceeds max length 100
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'DELIVERYADDRESSNAME' ERRORCOLUMN, 
PWCROWID ROWID, 
7 CATEGORY, 
'DELIVERYADDRESSNAME exceeds max length 100' ERRORDESC, 
DELIVERYADDRESSNAME ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE LEN(DELIVERYADDRESSNAME) > 100;

-- EMAIL exceeds max length 80
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderHeaderV2Entity' TABLEID, 
'EMAIL' ERRORCOLUMN, 
PWCROWID ROWID, 
7 CATEGORY, 
'EMAIL exceeds max length 80' ERRORDESC, 
EMAIL ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderHeaderV2Entity A
WHERE LEN(EMAIL) > 80;

EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_PurchPurchaseOrderHeaderV2Entity'
END
