CREATE OR ALTER PROCEDURE PWC_SP_Validate_PurchPurchaseOrderLineV2Entity
AS
BEGIN



-- LINENUMBER is not an integer number
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'LINENUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
2 CATEGORY, 
'LINENUMBER is not an integer number' ERRORDESC, 
LINENUMBER ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
LINENUMBER LIKE '%[^0-9]%' AND LINENUMBER IS NOT NULL;

-- Mandatory field missing:
-- PURCHASEORDERNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'PURCHASEORDERNUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
1 CATEGORY, 
'PURCHASEORDERNUMBER is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
PURCHASEORDERNUMBER = '' OR PURCHASEORDERNUMBER IS NULL;

-- ITEMNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'ITEMNUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
1 CATEGORY, 
'ITEMNUMBER is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
ITEMNUMBER = '' OR ITEMNUMBER IS NULL;

-- Business required fields missing:
-- LINENUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'LINENUMBER' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'LINENUMBER is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
LINENUMBER = '' OR LINENUMBER IS NULL;

-- SALESTAXITEMGROUPCODE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'SALESTAXITEMGROUPCODE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'SALESTAXITEMGROUPCODE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
SALESTAXITEMGROUPCODE = '' OR SALESTAXITEMGROUPCODE IS NULL;

-- LINEDESCRIPTION is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'LINEDESCRIPTION' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'LINEDESCRIPTION is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
LINEDESCRIPTION = '' OR LINEDESCRIPTION IS NULL;

-- ORDEREDPURCHASEQUANTITY is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'ORDEREDPURCHASEQUANTITY' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'ORDEREDPURCHASEQUANTITY is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
ORDEREDPURCHASEQUANTITY = '' OR ORDEREDPURCHASEQUANTITY IS NULL;

-- PURCHASEPRICE is blank
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'PURCHASEPRICE' ERRORCOLUMN, 
PWCROWID ROWID, 
8 CATEGORY, 
'PURCHASEPRICE is blank' ERRORDESC, 
'' ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
PURCHASEPRICE = '' OR PURCHASEPRICE IS NULL;







-- Duplicate occurrence:
-- PURCHASEORDERNUMBER, LINENUMBER has duplicate values
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
    '(PURCHASEORDERNUMBER, LINENUMBER)' ERRORCOLUMN, 
    PWCROWID ROWID, 
    3 CATEGORY, 
    CASE 
        WHEN LEN(PURCHASEORDERNUMBER) > 20 THEN 
            'PURCHASEORDERNUMBER, LINENUMBER has duplicate values upon truncation'
        ELSE 
            'PURCHASEORDERNUMBER, LINENUMBER has duplicate values'
    END ERRORDESC, 
    CONCAT('(', PURCHASEORDERNUMBER, ', ', LINENUMBER, ')') ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE 
    CONCAT(LEFT(PURCHASEORDERNUMBER, 20), LINENUMBER, DATAAREAID) IN (
    SELECT CONCAT(LEFT(PURCHASEORDERNUMBER, 20), LINENUMBER, DATAAREAID) 
    FROM PWC_T_PurchPurchaseOrderLineV2Entity
    GROUP BY LEFT(PURCHASEORDERNUMBER, 20), LINENUMBER, DATAAREAID 
    HAVING COUNT(*) > 1
);




-- PURCHASEORDERNUMBER validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.PURCHASEORDERNUMBER) = 0 THEN 'PURCHASEORDERNUMBER'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PURCHASEORDERNUMBER,[PWC_T_PurchPurchaseOrderHeaderV2Entity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.PURCHASEORDERNUMBER) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.PURCHASEORDERNUMBER) = 0 THEN 'PURCHASEORDERNUMBER is not present in PURCHASEORDERNUMBER of PWC_T_PurchPurchaseOrderHeaderV2Entity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_PurchPurchaseOrderHeaderV2Entity has error(s) in corresponding PURCHASEORDERNUMBER'
        END ERRORDESC,
        A.PURCHASEORDERNUMBER ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderLineV2Entity A
    LEFT JOIN PWC_T_PurchPurchaseOrderHeaderV2Entity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.PURCHASEORDERNUMBER = B.PURCHASEORDERNUMBER
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_PurchPurchaseOrderHeaderV2Entity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.PURCHASEORDERNUMBER IS NOT NULL AND A.PURCHASEORDERNUMBER != ''
    GROUP BY A.PWCROWID, A.PURCHASEORDERNUMBER, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- ITEMNUMBER validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.ITEMNUMBER) = 0 THEN 'ITEMNUMBER'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'ITEMNUMBER,[PWC_T_EcoResReleasedProductV2Entity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.ITEMNUMBER) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.ITEMNUMBER) = 0 THEN 'ITEMNUMBER is not present in ITEMNUMBER of PWC_T_EcoResReleasedProductV2Entity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_EcoResReleasedProductV2Entity has error(s) in corresponding ITEMNUMBER'
        END ERRORDESC,
        A.ITEMNUMBER ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderLineV2Entity A
    LEFT JOIN PWC_T_EcoResReleasedProductV2Entity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.ITEMNUMBER = B.ITEMNUMBER
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_EcoResReleasedProductV2Entity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.ITEMNUMBER IS NOT NULL AND A.ITEMNUMBER != ''
    GROUP BY A.PWCROWID, A.ITEMNUMBER, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- PURCHASEUNITSYMBOL validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.UnitSymbol) = 0 THEN 'PURCHASEUNITSYMBOL'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PURCHASEUNITSYMBOL,[PWC_T_UnitOfMeasureEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.UnitSymbol) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.UnitSymbol) = 0 THEN 'PURCHASEUNITSYMBOL is not present in UnitSymbol of PWC_T_UnitOfMeasureEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_UnitOfMeasureEntity has error(s) in corresponding UnitSymbol'
        END ERRORDESC,
        A.PURCHASEUNITSYMBOL ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderLineV2Entity A
    LEFT JOIN PWC_T_UnitOfMeasureEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.PURCHASEUNITSYMBOL = B.UnitSymbol
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_UnitOfMeasureEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.PURCHASEUNITSYMBOL IS NOT NULL AND A.PURCHASEUNITSYMBOL != ''
    GROUP BY A.PWCROWID, A.PURCHASEUNITSYMBOL, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- SALESTAXITEMGROUPCODE validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
        CASE 
            WHEN COUNT(B.TAXITEMGROUP) = 0 THEN 'SALESTAXITEMGROUPCODE'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'SALESTAXITEMGROUPCODE,[PWC_T_TaxItemGroupHeadingEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.TAXITEMGROUP) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.TAXITEMGROUP) = 0 THEN 'SALESTAXITEMGROUPCODE is not present in ITEMSALESTAXGROUP of PWC_T_TaxItemGroupHeadingEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_T_TaxItemGroupHeadingEntity has error(s) in corresponding ITEMSALESTAXGROUP'
        END ERRORDESC,
        A.SALESTAXITEMGROUPCODE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_PurchPurchaseOrderLineV2Entity A
    LEFT JOIN PWC_T_TaxItemGroupHeadingEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') 
        AND A.SALESTAXITEMGROUPCODE = B.TAXITEMGROUP
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_T_TaxItemGroupHeadingEntity' 
        AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
        AND B.PWCROWID = E.ROWID
    WHERE A.SALESTAXITEMGROUPCODE IS NOT NULL AND A.SALESTAXITEMGROUPCODE != ''
    GROUP BY A.PWCROWID, A.SALESTAXITEMGROUPCODE, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;





-- String length exceeded maximum
-- LINEDESCRIPTION exceeds max length 1000
INSERT INTO PWCERRORTABLE
SELECT 
'PWC_T_PurchPurchaseOrderLineV2Entity' TABLEID, 
'LINEDESCRIPTION' ERRORCOLUMN, 
PWCROWID ROWID, 
7 CATEGORY, 
'LINEDESCRIPTION exceeds max length 1000' ERRORDESC, 
LINEDESCRIPTION ERRORVALUE,
A.DATAAREAID DATAAREAID
FROM PWC_T_PurchPurchaseOrderLineV2Entity A
WHERE LEN(LINEDESCRIPTION) > 1000;

EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_PurchPurchaseOrderLineV2Entity'
END
