CREATE OR ALTER PROCEDURE PWC_SP_Validate_TradeOpenTradeAgreementJournalHeaderV2Entity
AS
BEGIN

-- Mandatory field missing:
-- TRADEAGREEMENTJOURNALNAMEID is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity' TABLEID, 
    'TRADEAGREEMENTJOURNALNAMEID' ERRORCOLUMN, 
    PWCROWID ROWID, 
    1 CATEGORY, 
    'TRADEAGREEMENTJOURNALNAMEID is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity A
WHERE 
    TRADEAGREEMENTJOURNALNAMEID = '' OR TRADEAGREEMENTJOURNALNAMEID IS NULL;




-- Business reqd fields missing
-- DEFAULTTRADEAGREEMENTTYPE is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity' TABLEID, 
    'DEFAULTTRADEAGREEMENTTYPE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    1 CATEGORY, 
    'DEFAULTTRADEAGREEMENTTYPE is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity A
WHERE 
    DEFAULTTRADEAGREEMENTTYPE = '' OR DEFAULTTRADEAGREEMENTTYPE IS NULL;

-- JOURNALNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity' TABLEID, 
    'JOURNALNUMBER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    1 CATEGORY, 
    'JOURNALNUMBER is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity A
WHERE 
    JOURNALNUMBER = '' OR JOURNALNUMBER IS NULL;




-- Duplicate occurrence:
-- JOURNALNUMBER, DATAAREAID has duplicates
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity' TABLEID, 
    'JOURNALNUMBER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    3 CATEGORY, 
    CASE 
        WHEN LEN(JOURNALNUMBER) > 20 THEN 
            'JOURNALNUMBER has duplicate values upon truncation in ' + DATAAREAID
        ELSE 
            'JOURNALNUMBER has duplicate values in ' + DATAAREAID
    END ERRORDESC, 
    JOURNALNUMBER ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity A
WHERE 
    CONCAT(LEFT(JOURNALNUMBER, 20), DATAAREAID) IN (
    SELECT CONCAT(LEFT(JOURNALNUMBER, 20), DATAAREAID) 
    FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity
    GROUP BY LEFT(JOURNALNUMBER, 20), DATAAREAID 
    HAVING COUNT(*) > 1
);





-- String length exceeded maximum:
-- TRADEAGREEMENTJOURNALNAMEID exceeds max length 10
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity' TABLEID, 
    'TRADEAGREEMENTJOURNALNAMEID' ERRORCOLUMN, 
    PWCROWID ROWID, 
    7 CATEGORY, 
    'TRADEAGREEMENTJOURNALNAMEID exceeds max length 10' ERRORDESC, 
    TRADEAGREEMENTJOURNALNAMEID ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity A
WHERE LEN(TRADEAGREEMENTJOURNALNAMEID) > 10;

-- JOURNALDESCRIPTION exceeds max length 60
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity' TABLEID, 
    'JOURNALDESCRIPTION' ERRORCOLUMN, 
    PWCROWID ROWID, 
    7 CATEGORY, 
    'JOURNALDESCRIPTION exceeds max length 60' ERRORDESC, 
    JOURNALDESCRIPTION ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity A
WHERE LEN(JOURNALDESCRIPTION) > 60;

-- JOURNALNUMBER exceeds max length 20
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity' TABLEID, 
    'JOURNALNUMBER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    7 CATEGORY, 
    'JOURNALNUMBER exceeds max length 20' ERRORDESC, 
    JOURNALNUMBER ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity A
WHERE LEN(JOURNALNUMBER) > 20;

EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_TradeOpenTradeAgreementJournalHeaderV2Entity'
END
