CREATE OR ALTER PROCEDURE PWC_SP_Validate_VendVendorGroupEntity
AS
BEGIN

-- Mandatory fields missing
	-- VENDORGROUPID is blank
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_VendVendorGroupEntity' TABLEID, 
		'VENDORGROUPID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		1 CATEGORY, 
		'VENDORGROUPID is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_VendVendorGroupEntity A
	WHERE 
		VENDORGROUPID = '' OR VENDORGROUPID IS NULL;



--Business required fields missing field missing:
	-- DESCRIPTION is blank
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_VendVendorGroupEntity' TABLEID, 
		'DESCRIPTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		8 CATEGORY, 
		'DESCRIPTION is blank' ERRORDESC, 
		'' ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_VendVendorGroupEntity A
	WHERE 
		DESCRIPTION = '' OR DESCRIPTION IS NULL;


--Duplicate occurrence:
	-- VENDORGROUPID has duplicates
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_VendVendorGroupEntity' TABLEID, 
		'VENDORGROUPID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		3 CATEGORY, 
		CASE 
			WHEN LEN(VENDORGROUPID) > 10 THEN 
				'VENDORGROUPID has duplicate values upon truncation in ' + DATAAREAID
			ELSE 
				'VENDORGROUPID has duplicate values in ' + DATAAREAID
		END ERRORDESC, 
		VENDORGROUPID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_VendVendorGroupEntity A
	WHERE 
		CONCAT(LEFT(VENDORGROUPID, 10), DATAAREAID) IN (
		SELECT CONCAT(LEFT(VENDORGROUPID, 10), DATAAREAID) 
		FROM PWC_T_VendVendorGroupEntity
		GROUP BY LEFT(VENDORGROUPID, 10), DATAAREAID 
		HAVING COUNT(*) > 1
		);


-- String length exceeded maximum
	-- VENDORGROUPID exceeds max length 10
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_VendVendorGroupEntity' TABLEID, 
		'VENDORGROUPID' ERRORCOLUMN, 
		PWCROWID ROWID, 
		7 CATEGORY, 
		'VENDORGROUPID exceeds max length 10' ERRORDESC, 
		VENDORGROUPID ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_VendVendorGroupEntity A
	WHERE LEN(VENDORGROUPID) > 10;

	-- DESCRIPTION exceeds max length 60
	INSERT INTO PWCERRORTABLE
	SELECT 
		'PWC_T_VendVendorGroupEntity' TABLEID, 
		'DESCRIPTION' ERRORCOLUMN, 
		PWCROWID ROWID, 
		7 CATEGORY, 
		'DESCRIPTION exceeds max length 60' ERRORDESC, 
		DESCRIPTION ERRORVALUE,
		A.DATAAREAID DATAAREAID
	FROM PWC_T_VendVendorGroupEntity A
	WHERE LEN(DESCRIPTION) > 60;

	EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_VendVendorGroupEntity'
END