CREATE OR ALTER PROCEDURE PWC_SP_Validate_VendorPaymentJournalLineEntity
AS
BEGIN

-- Invalid data format:
-- TRANSACTIONDATE HAS WRONG DATE FORMAT
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'TRANSACTIONDATE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    2 CATEGORY, 
    'TRANSACTIONDATE has wrong date format' ERRORDESC, 
    TRANSACTIONDATE ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    TRANSACTIONDATE IS NOT NULL AND ISDATE(TRANSACTIONDATE) = 0;

-- ISPREPAYMENT HAS WRONG BOOLEAN FORMAT
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'ISPREPAYMENT' ERRORCOLUMN, 
    PWCROWID ROWID, 
    2 CATEGORY, 
    'ISPREPAYMENT has wrong boolean format' ERRORDESC, 
    ISPREPAYMENT ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    UPPER(ISPREPAYMENT) NOT IN ('YES', 'NO');

-- LINENUMBER has wrong Real format
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'LINENUMBER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    2 CATEGORY, 
    'LINENUMBER has wrong Real format' ERRORDESC, 
    LINENUMBER ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE LINENUMBER LIKE '%[^0-9.]%';

-- CREDITAMOUNT has wrong Real format
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'CREDITAMOUNT' ERRORCOLUMN, 
    PWCROWID ROWID, 
    2 CATEGORY, 
    'CREDITAMOUNT has wrong Real format' ERRORDESC, 
    CREDITAMOUNT ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE CREDITAMOUNT LIKE '%[^0-9.]%';

-- DEBITAMOUNT has wrong Real format
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'DEBITAMOUNT' ERRORCOLUMN, 
    PWCROWID ROWID, 
    2 CATEGORY, 
    'DEBITAMOUNT has wrong Real format' ERRORDESC, 
    DEBITAMOUNT ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE DEBITAMOUNT LIKE '%[^0-9.]%';

-- EXCHANGERATE has wrong Real format
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'EXCHANGERATE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    2 CATEGORY, 
    'EXCHANGERATE has wrong Real format' ERRORDESC, 
    EXCHANGERATE ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE EXCHANGERATE LIKE '%[^0-9.]%';



-- Other system checks
-- Both CREDITAMOUNT and DEBITAMOUNT cannot be 0 or NULL
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    '(CREDITAMOUNT, DEBITAMOUNT)' ERRORCOLUMN, 
    PWCROWID ROWID, 
    6 CATEGORY, 
    'Both CREDITAMOUNT and DEBITAMOUNT cannot be 0 or NULL' ERRORDESC, 
    CONCAT('(', CREDITAMOUNT, ', ', DEBITAMOUNT, ')') ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    (CREDITAMOUNT = '0' OR CREDITAMOUNT IS NULL) AND (DEBITAMOUNT = '0' OR DEBITAMOUNT IS NULL);

-- Both CREDITAMOUNT and DEBITAMOUNT cannot be filled/non-zero
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    '(CREDITAMOUNT, DEBITAMOUNT)' ERRORCOLUMN, 
    PWCROWID ROWID, 
    6 CATEGORY, 
    'Both CREDITAMOUNT and DEBITAMOUNT cannot be filled/non-zero' ERRORDESC, 
    CONCAT('(', CREDITAMOUNT, ', ', DEBITAMOUNT, ')') ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    (CREDITAMOUNT IS NOT NULL AND CREDITAMOUNT NOT LIKE '0') AND (DEBITAMOUNT IS NOT NULL AND DEBITAMOUNT NOT LIKE '0');




-- Mandatory field missing
-- LINENUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'LINENUMBER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    1 CATEGORY, 
    'LINENUMBER is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    LINENUMBER = '' OR LINENUMBER IS NULL;

-- CURRENCYCODE is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'CURRENCYCODE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    1 CATEGORY, 
    'CURRENCYCODE is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    CURRENCYCODE = '' OR CURRENCYCODE IS NULL;

-- JOURNALBATCHNUMBER is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'JOURNALBATCHNUMBER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    1 CATEGORY, 
    'JOURNALBATCHNUMBER is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    JOURNALBATCHNUMBER = '' OR JOURNALBATCHNUMBER IS NULL;




-- Business reqd field missing
-- ACCOUNTDISPLAYVALUE is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'ACCOUNTDISPLAYVALUE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    8 CATEGORY, 
    'ACCOUNTDISPLAYVALUE is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    ACCOUNTDISPLAYVALUE = '' OR ACCOUNTDISPLAYVALUE IS NULL;

-- OFFSETACCOUNTDISPLAYVALUE is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'OFFSETACCOUNTDISPLAYVALUE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    8 CATEGORY, 
    'OFFSETACCOUNTDISPLAYVALUE is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    OFFSETACCOUNTDISPLAYVALUE = '' OR OFFSETACCOUNTDISPLAYVALUE IS NULL;

-- COMPANY is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'COMPANY' ERRORCOLUMN, 
    PWCROWID ROWID, 
    8 CATEGORY, 
    'COMPANY is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    COMPANY = '' OR COMPANY IS NULL;

-- PAYMENTMETHODNAME is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'PAYMENTMETHODNAME' ERRORCOLUMN, 
    PWCROWID ROWID, 
    8 CATEGORY, 
    'PAYMENTMETHODNAME is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    PAYMENTMETHODNAME = '' OR PAYMENTMETHODNAME IS NULL;

-- POSTINGPROFILE is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'POSTINGPROFILE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    8 CATEGORY, 
    'POSTINGPROFILE is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    POSTINGPROFILE = '' OR POSTINGPROFILE IS NULL;

-- TRANSACTIONDATE is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'TRANSACTIONDATE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    8 CATEGORY, 
    'TRANSACTIONDATE is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    TRANSACTIONDATE = '' OR TRANSACTIONDATE IS NULL;

-- VOUCHER is blank
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'VOUCHER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    8 CATEGORY, 
    'VOUCHER is blank' ERRORDESC, 
    '' ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    VOUCHER = '' OR VOUCHER IS NULL;







-- Duplicate occurrence:
-- LINENUMBER, JOURNALBATCHNUMBER, DATAAREAID has duplicates
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    '(LINENUMBER, JOURNALBATCHNUMBER, DATAAREAID)' ERRORCOLUMN, 
    PWCROWID ROWID, 
    3 CATEGORY, 
    CASE 
        WHEN LEN(JOURNALBATCHNUMBER) > 20 THEN 
            'LINENUMBER, JOURNALBATCHNUMBER has duplicate values upon truncation in ' + DATAAREAID
        ELSE 
            'LINENUMBER, JOURNALBATCHNUMBER has duplicate values in ' + DATAAREAID
    END ERRORDESC, 
    CONCAT('(', LINENUMBER, ', ', JOURNALBATCHNUMBER, ')') ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    CONCAT(LINENUMBER, LEFT(JOURNALBATCHNUMBER, 20), DATAAREAID) IN (
    SELECT CONCAT(LINENUMBER, LEFT(JOURNALBATCHNUMBER, 20), DATAAREAID) 
    FROM PWC_T_VendorPaymentJournalLineEntity
    GROUP BY LINENUMBER, LEFT(JOURNALBATCHNUMBER, 20), DATAAREAID 
    HAVING COUNT(*) > 1
);




-- Invalid submaster reference
-- COMPANY validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
        CASE 
            WHEN COUNT(B.LEGALENTITYID) = 0 THEN 'COMPANY'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'COMPANY,[PWC_E_OMLegalEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.LEGALENTITYID) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.LEGALENTITYID) = 0 THEN 'COMPANY is not present in LEGALENTITYID of PWC_E_OMLegalEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_E_OMLegalEntity has error(s) in corresponding LEGALENTITYID'
        END ERRORDESC,
        A.COMPANY ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_VendorPaymentJournalLineEntity A
    LEFT JOIN PWC_E_OMLegalEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') AND A.COMPANY = B.LEGALENTITYID
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_E_OMLegalEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
            AND B.PWCROWID = E.ROWID
    WHERE 
        A.COMPANY IS NOT NULL AND A.COMPANY != ''
    GROUP BY A.PWCROWID, A.COMPANY, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- CURRENCYCODE validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
        CASE 
            WHEN COUNT(B.CURRENCYCODE) = 0 THEN 'CURRENCYCODE'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'CURRENCYCODE,[PWC_E_CurrencyEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.CURRENCYCODE) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.CURRENCYCODE) = 0 THEN 'CURRENCYCODE is not present in CURRENCYCODE of PWC_E_CurrencyEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_E_CurrencyEntity has error(s) in corresponding CURRENCYCODE'
        END ERRORDESC,
        A.CURRENCYCODE ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_VendorPaymentJournalLineEntity A
    LEFT JOIN PWC_E_CurrencyEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') AND A.CURRENCYCODE = B.CURRENCYCODE
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_E_CurrencyEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
            AND B.PWCROWID = E.ROWID
    WHERE 
        A.CURRENCYCODE IS NOT NULL AND A.CURRENCYCODE != ''
    GROUP BY A.PWCROWID, A.CURRENCYCODE, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- THIRDPARTYBANKACCOUNTID validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
        CASE 
            WHEN COUNT(B.BankAccountId) = 0 THEN 'THIRDPARTYBANKACCOUNTID'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'THIRDPARTYBANKACCOUNTID,[PWC_E_BankAccountEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.BankAccountId) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.BankAccountId) = 0 THEN 'THIRDPARTYBANKACCOUNTID is not present in BankAccountId of PWC_E_BankAccountEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_E_BankAccountEntity has error(s) in corresponding BankAccountId'
        END ERRORDESC,
        A.THIRDPARTYBANKACCOUNTID ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_VendorPaymentJournalLineEntity A
    LEFT JOIN PWC_E_BankAccountEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') AND A.THIRDPARTYBANKACCOUNTID = B.BankAccountId
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_E_BankAccountEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
            AND B.PWCROWID = E.ROWID
    WHERE 
        A.THIRDPARTYBANKACCOUNTID IS NOT NULL AND A.THIRDPARTYBANKACCOUNTID != ''
    GROUP BY A.PWCROWID, A.THIRDPARTYBANKACCOUNTID, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- PAYMENTMETHODNAME validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
        CASE 
            WHEN COUNT(B.Name) = 0 THEN 'PAYMENTMETHODNAME'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PAYMENTMETHODNAME,[PWC_E_VendorPaymentMethodEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.Name) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.Name) = 0 THEN 'PAYMENTMETHODNAME is not present in Name of PWC_E_VendorPaymentMethodEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_E_VendorPaymentMethodEntity has error(s) in corresponding Name'
        END ERRORDESC,
        A.PAYMENTMETHODNAME ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_VendorPaymentJournalLineEntity A
    LEFT JOIN PWC_E_VendorPaymentMethodEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') AND A.PAYMENTMETHODNAME = B.Name
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_E_VendorPaymentMethodEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
            AND B.PWCROWID = E.ROWID
    WHERE 
        A.PAYMENTMETHODNAME IS NOT NULL AND A.PAYMENTMETHODNAME != ''
    GROUP BY A.PWCROWID, A.PAYMENTMETHODNAME, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;

-- JOURNALBATCHNUMBER validation
INSERT INTO PWCERRORTABLE
SELECT * FROM (
    SELECT 
        'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
        CASE 
            WHEN COUNT(B.JOURNALBATCHNUMBER) = 0 THEN 'JOURNALBATCHNUMBER'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'JOURNALBATCHNUMBER,[PWC_E_VendorPaymentJournalHeaderEntity]'
        END ERRORCOLUMN, 
        A.PWCROWID ROWID, 
        CASE 
            WHEN COUNT(B.JOURNALBATCHNUMBER) = 0 THEN 4
            WHEN COUNT(E.CATEGORY) <> 0 THEN 5
        END CATEGORY, 
        CASE 
            WHEN COUNT(B.JOURNALBATCHNUMBER) = 0 THEN 'JOURNALBATCHNUMBER is not present in JOURNALBATCHNUMBER of PWC_E_VendorPaymentJournalHeaderEntity'
            WHEN COUNT(E.CATEGORY) <> 0 THEN 'PWC_E_VendorPaymentJournalHeaderEntity has error(s) in corresponding JOURNALBATCHNUMBER'
        END ERRORDESC,
        A.JOURNALBATCHNUMBER ERRORVALUE,
        A.DATAAREAID DATAAREAID
    FROM PWC_T_VendorPaymentJournalLineEntity A
    LEFT JOIN PWC_E_VendorPaymentJournalHeaderEntity B
        ON (B.DATAAREAID = A.DATAAREAID OR UPPER(A.DATAAREAID) = 'GLOBAL' OR UPPER(B.DATAAREAID) = 'GLOBAL') AND A.JOURNALBATCHNUMBER = B.JOURNALBATCHNUMBER
    LEFT JOIN PWCERRORTABLE E
        ON E.TABLEID = 'PWC_E_VendorPaymentJournalHeaderEntity' AND E.CATEGORY IN (SELECT ID FROM PWCCATEGORY WHERE STATUS = 3)
            AND B.PWCROWID = E.ROWID
    WHERE 
        A.JOURNALBATCHNUMBER IS NOT NULL AND A.JOURNALBATCHNUMBER != ''
    GROUP BY A.PWCROWID, A.JOURNALBATCHNUMBER, A.DATAAREAID
) a
WHERE CATEGORY IS NOT NULL;









-- Enum value check
-- OFFSETACCOUNTTYPE has invalid enum values
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'OFFSETACCOUNTTYPE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    2 CATEGORY, 
    'OFFSETACCOUNTTYPE has invalid enum values' ERRORDESC, 
    OFFSETACCOUNTTYPE ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE 
    OFFSETACCOUNTTYPE IS NOT NULL AND OFFSETACCOUNTTYPE NOT IN (
        SELECT MEMBERNAME 
        FROM RETAILENUMVALUETABLE 
        WHERE ENUMNAME LIKE 'LedgerJournalACType'
    );





-- String length exceeded maximum:
-- BANKTRANSACTIONTYPE exceeds max length 10
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'BANKTRANSACTIONTYPE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    7 CATEGORY, 
    'BANKTRANSACTIONTYPE exceeds max length 10' ERRORDESC, 
    BANKTRANSACTIONTYPE ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE LEN(BANKTRANSACTIONTYPE) > 10;

-- PAYMENTREFERENCE exceeds max length 35
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'PAYMENTREFERENCE' ERRORCOLUMN, 
    PWCROWID ROWID, 
    7 CATEGORY, 
    'PAYMENTREFERENCE exceeds max length 35' ERRORDESC, 
    PAYMENTREFERENCE ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE LEN(PAYMENTREFERENCE) > 35;

-- TRANSACTIONTEXT exceeds max length 512
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'TRANSACTIONTEXT' ERRORCOLUMN, 
    PWCROWID ROWID, 
    7 CATEGORY, 
    'TRANSACTIONTEXT exceeds max length 512' ERRORDESC, 
    TRANSACTIONTEXT ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE LEN(TRANSACTIONTEXT) > 512;

-- VOUCHER exceeds max length 20
INSERT INTO PWCERRORTABLE
SELECT 
    'PWC_T_VendorPaymentJournalLineEntity' TABLEID, 
    'VOUCHER' ERRORCOLUMN, 
    PWCROWID ROWID, 
    7 CATEGORY, 
    'VOUCHER exceeds max length 20' ERRORDESC, 
    VOUCHER ERRORVALUE,
    A.DATAAREAID DATAAREAID
FROM PWC_T_VendorPaymentJournalLineEntity A
WHERE LEN(VOUCHER) > 20;

EXEC PWC_SP_CALCULATESUCCESSFULCOUNT @TableName = 'PWC_T_VendorPaymentJournalLineEntity'
END
