DROP TABLE [dbo].[PWC_T_LOGISTICSADDRESSCITYENTITY]
CREATE TABLE [dbo].[PWC_T_LOGISTICSADDRESSCITYENTITY](
	[PWCROWID] [int] IDENTITY(1,1) PRIMARY KEY,
	[NAME] [NVARCHAR](3000),
	[DESCRIPTION] [NVARCHAR](3000),
	[BRAZILCITYCODE] [NVARCHAR](3000),
	[CITYKEY] [NVARCHAR](3000),
	[CITYINKANA] [NVARCHAR](3000),
	[COUNTRYREGIONID] [NVARCHAR](3000),
	[STATEID] [NVARCHAR](3000),
	[COUNTYID] [NVARCHAR](3000),
	[ITALYCITYCODE] [NVARCHAR](3000),
	[ITALYMUNICIPALITYCODE] [NVARCHAR](3000),
	DATAAREAID [nvarchar](6) DEFAULT 'GLOBAL'
)