DROP TABLE [dbo].[PWC_T_LOGISTICSADDRESSCOUNTRYREGIONENTITY]
CREATE TABLE [dbo].[PWC_T_LOGISTICSADDRESSCOUNTRYREGIONENTITY](
	[PWCROWID] [int] IDENTITY(1,1) PRIMARY KEY,
	[COUNTRYREGION] [nvarchar](3000),
	[ADDRESSFORMAT] [nvarchar](3000),
	[TIMEZONE] [nvarchar](3000),
	[USEZIPPLUS4] [nvarchar](3000),
	[ISOCODE] [nvarchar](3000),
	[CURRENCYCODE] [nvarchar](3000),
	[PARENTCOUNTRYREGION] [nvarchar](3000),
	[BRAZILCENTRALBANKCOUNTRYCODE] [nvarchar](3000),
	[OKSMCODE_RU] [nvarchar](3000),
	DATAAREAID [nvarchar](6) DEFAULT 'GLOBAL'
)