DROP TABLE [dbo].[PWC_T_CURRENCYENTITY]
CREATE TABLE [dbo].[PWC_T_CURRENCYENTITY](
	[PWCROWID] [int] IDENTITY(1,1) PRIMARY KEY,
	[CURRENCYCODE] [nvarchar](3000),
	[REFERENCECURRENCYFORTRIANGULATION] [nvarchar](3000),
	[GENERALROUNDINGRULE] [nvarchar](3000),
	[SYMBOL] [nvarchar](3000),
	[NAME] [nvarchar](3000),
	[CURRENCYGENDER] [nvarchar](3000),
	[ROUNDINGRULEFIXEDASSETDEPRECIATION] [nvarchar](3000),
	[ROUNDINGMETHODFIXEDASSETDEPRECIATION] [nvarchar](3000),
	[ROUNDINGMETHODPRICES] [nvarchar](3000),
	[ROUNDINGMETHODPURCHASEORDERS] [nvarchar](3000),
	[ROUNDINGMETHODSALESORDERS] [nvarchar](3000),
	[ROUNDINGRULEPRICES] [nvarchar](3000),
	[ROUNDINGRULEPURCHASEORDERS] [nvarchar](3000),
	[ROUNDINGRULESALESORDERS] [nvarchar](3000),
	[DECIMALSCOUNT_MX] [nvarchar](3000),
	DATAAREAID [nvarchar](6) DEFAULT 'GLOBAL'
)
