DROP TABLE [dbo].[PWC_T_LOGISTICSADDRESSSTATEENTITY]
CREATE TABLE [dbo].[PWC_T_LOGISTICSADDRESSSTATEENTITY](
	[PWCROWID] [int] IDENTITY(1,1) PRIMARY KEY,
	[NAME][nvarchar](3000),
	[TIMEZONE][nvarchar](3000),
	[INTRASTATCODE][nvarchar](3000),
	[BRAZILSTATECODE][nvarchar](3000),
	[COUNTRYREGIONID][nvarchar](3000),
	[STATE][nvarchar](3000),
	[DEFAULTSTATEFORCOUNTRYREGION][nvarchar](3000),
	DATAAREAID [nvarchar](6) DEFAULT 'GLOBAL'
)